(function(){const frame=document.getElementById('presentation');if(!frame)return;frame.addEventListener('load',()=>{try{
 const w=frame.contentWindow,d=w.document,C=w.CSI11;if(!C)return;const slides=C.slides;
 const css=`.csi-lang{display:flex;align-items:center;padding:3px;border:1px solid var(--line);background:var(--white);border-radius:999px}.csi-lang button{border:0;background:transparent;color:var(--muted);font-size:.72rem;font-weight:950;border-radius:999px;padding:6px 8px;cursor:pointer}.csi-lang button.active{background:var(--accent);color:#fff}.notes-panel.csi-notes{position:fixed!important;left:42px!important;right:auto!important;top:90px!important;bottom:auto!important;width:480px!important;height:520px!important;max-width:90vw!important;max-height:82vh!important;min-width:340px!important;min-height:260px!important;resize:both!important;overflow:auto!important;border-radius:24px!important;padding:0!important}.notes-panel.csi-notes .panel-head{position:sticky;top:0;z-index:2;padding:15px 16px;margin:0!important;background:color-mix(in srgb,var(--cream) 95%,var(--accent-pale));border-bottom:1px solid var(--line);cursor:move;user-select:none}.notes-panel.csi-notes .notes-body{padding:18px 20px!important;line-height:1.55!important}.csi-note-title{font:800 1.2rem Georgia,serif;color:var(--accent-strong);margin-bottom:10px}.csi-note-block{padding:12px 14px;border-radius:16px;background:var(--accent-pale);border:1px solid var(--line);margin:10px 0}.csi-note-block strong{color:var(--accent-strong)}.csi-note-next{margin-top:16px;padding-top:12px;border-top:1px solid var(--line);font-size:.8rem;color:var(--muted)}#csiQVault{position:fixed;inset:0;z-index:3000;background:linear-gradient(180deg,var(--cream),var(--accent-pale));display:none;overflow:auto;color:var(--text)}.csi-q-inner{width:min(1660px,100%);min-height:100vh;margin:auto;padding:92px clamp(38px,4.2vw,82px) 70px}.csi-q-head{display:flex;justify-content:space-between;align-items:center}.csi-q-close{border:1px solid var(--line);background:var(--white);color:var(--text);border-radius:999px;padding:10px 15px;font-weight:900;cursor:pointer}.csi-q-blank{margin-top:30px;min-height:58vh;border:1px dashed var(--line);border-radius:28px;background:var(--white)}@media(max-width:820px){.notes-panel.csi-notes{left:5vw!important;width:90vw!important}}`;const st=d.createElement('style');st.textContent=css;d.head.appendChild(st);
 const pack=(core,pts,trans)=>`<div class="csi-note-block"><strong>Message central</strong><br>${core}</div><div class="csi-note-block"><strong>À dire</strong><br>${pts.map(x=>'• '+x).join('<br>')}</div>${trans?`<div class="csi-note-block"><strong>Transition</strong><br>${trans}</div>`:''}`;
 const notesFR=s=>{const t=s.title||'';
  if(t.includes('espace-temps pour les odeurs'))return pack('Présenter la question de thèse comme le fil conducteur du CSI.',['Situer le doctorat au CSGA et dans l’équipe DOCC.','Nommer l’encadrement et les deux membres du CSI.','Annoncer le bilan scientifique, méthodologique et doctoral.'],'Passer au parcours puis à la question scientifique.');
  if(t.includes('parcours généraliste'))return pack('Montrer la continuité entre psychologie cognitive, multisensorialité et olfaction.',['Rester bref sur chaque diplôme.','Insister sur la montée en autonomie expérimentale.','Relier le Master aux questions actuelles.'],'Introduire le cadre doctoral.');
  if(t.includes('Deux axes'))return pack('Clarifier la complémentarité des deux axes.',['Axe 1 : relations spatio-temporelles entre modalités.','Axe 2 : influence des odeurs sur la perception visuelle et auditive.','Les deux axes partagent des contraintes de synchronisation et de mesure.'],'Présenter ensuite le verrou temporel propre à l’olfaction.');
  if(t.includes('L\'olfaction complique'))return pack('Expliquer pourquoi le temps olfactif ne correspond pas au timestamp logiciel.',['Distinguer commande, délivrance, inspiration et perception.','Utiliser les cartes Sniff-0 et Spir-0 uniquement comme contexte visuel.','Relier cette difficulté à SOFT et TWIXOLF.'],'Entrer dans le programme expérimental.');
  if(t.includes('TWIXAV -'))return pack('Présenter TWIXAV comme référence audiovisuelle de l’Axe 1.',['Rappeler le jugement de simultanéité.','Indiquer que la zone de résultats recevra les courbes finales.','Mentionner le mémoire de M1 d’Alicia.'],'Passer aux effets préliminaires et à l’asymétrie.');
  if(t.includes('effet net de la durée'))return pack('Montrer que la manipulation temporelle produit des effets structurés.',['Commenter les trois effets statistiques sans surinterpréter.','Insister sur l’asymétrie comme question mécanistique.','Les courbes finales viendront dans la zone dédiée.'],'Introduire SOFT.');
  if(t.includes('SOFT -'))return pack('SOFT teste si l’asymétrie vient d’une différence de précision entre onset et offset.',['Préciser que l’étude est prête à démarrer.','Distinguer comportement, EEG et physiologie.','Garder les détails de triggers et de timing pour les questions.'],'Revenir ensuite à l’intégration olfactive avec TWIXOLF.');
  if(t.includes('Transposer la liaison'))return pack('TWIXOLF transpose la fenêtre temporelle d’intégration à l’olfaction.',['Préciser que l’étude est prête à démarrer.','Citer respiration, latence, habituation et intensité comme contrôles.','Le rétroplanning place OASIS avant TWIXOLF pour des raisons opérationnelles.'],'Passer à l’Axe 2.');
  if(t.includes('VIBEX -'))return pack('Présenter VIBEX comme référence visuelle de Boundary Extension.',['Rappeler le paradigme sans détailler toutes les conditions.','Montrer la zone réservée aux résultats.','Mentionner le mémoire de M1 d’Olivia.'],'Introduire OASIS.');
  if(t.includes('OASIS -'))return pack('OASIS teste la modulation olfactive de réponses spatiales d’approche-évitement.',['Préciser que l’étude est prête à démarrer.','Présenter comportement, EDA, ECG et respiration.','Souligner la réutilisation de l’infrastructure.'],'Passer à l’état consolidé des études centrales.');
  if(t.includes('État d\'avancement'))return pack('Donner une photographie simple de la maturité des études.',['TWIXAV et VIBEX : prétests terminés.','SOFT, OASIS et TWIXOLF : prêtes à démarrer.','Les extensions restent conditionnelles.'],'Passer aux contraintes expérimentales et à l’infrastructure.');
  if(t.includes('plateforme expérimentale'))return pack('Présenter l’infrastructure comme un système mutualisé.',['Une base PsychoPy et une logique de logs communes.','Olfaction, physiologie et EEG activés selon les études.','Objectif : reproductibilité et maintenabilité.'],'Détailler ensuite respiration et synchronisation.');
  if(t.includes('principales difficultés'))return pack('Montrer que les difficultés ont conduit à des choix méthodologiques concrets.',['Synchronisation olfactive.','Multiplication des dispositifs.','Standardisation des analyses.'],'Une fois ces contraintes posées, passer au bilan doctoral.');
  if(t.includes('Enseignements réalisés'))return pack('Présenter le bilan d’enseignement 2025-2026 de manière factuelle.',['40 h de TD en L1.','14 h de TER en L3.','6 h de TP Master en neurosciences, non intégrées au total valorisé.'],'Passer à la formation doctorale suivie.');
  if(t.includes('Formations suivies'))return pack('Montrer que la formation doctorale soutient le projet d’enseignant-chercheur.',['60 h réparties en 6 modules.','Poids important de la pédagogie universitaire.','Compléments en intégrité, documentation et valorisation.'],'Passer ensuite au programme opérationnel de l’année 2.');
  if(t.includes('Rétroplanning'))return pack('Présenter le calendrier comme une séquence de travail.',['SOFT en premier.','OASIS avant TWIXOLF.','Analyses TWIXAV/VIBEX et rédaction en parallèle.'],'Aborder ensuite enseignement et formation de l’année 2.');
  if(t.includes('Enseignements prévus'))return pack('Présenter les 58 h prévues pour 2026-2027.',['20 h L1 méthodologie expérimentale.','24 h L2 psychologie cognitive - attention.','14 h L3 TER multisensoriel.'],'Passer aux formations envisagées.');
  if(t.includes('Formations envisagées'))return pack('Présenter des priorités de formation sans inventer des modules non attribués.',['Pédagogie universitaire.','Méthodes et science ouverte.','Préparation au métier d’enseignant-chercheur.'],'Passer aux productions et actions de diffusion.');
  if(t.includes('Communications envisagées'))return pack('Présenter la diffusion après le cœur scientifique et technique.',['Nuit des chercheurs - septembre 2026.','Fête de la Science - octobre 2026.','Expérimentarium - mars 2027.','FJC et JDD - juin 2027.'],'Revenir aux arbitrages du CSI.');
  if(t.includes('décisions les plus utiles'))return pack('Ouvrir la discussion avec le comité.',['Ordre des études.','Charge de SOFT et faisabilité matérielle.','Priorités de valorisation.','Place des extensions et de la charge doctorale.'],'Laisser le comité intervenir puis conclure.');
  if(t.includes('Merci pour votre attention'))return pack('Clore sans ajouter de nouvelle information.',['Remercier le CSI et la direction de thèse.','Rester sur cette slide pendant les échanges de fin.'],'');
  return pack('Présenter uniquement le rôle de cette slide dans le fil logique.',['Décrire les éléments affichés.','Éviter les détails non nécessaires à la compréhension.','Relier le contenu à la slide suivante.'],'Poursuivre le récit sans revenir en arrière.');};
 slides.forEach(s=>{s.notes=notesFR(s);s._fr={section:s.section,kicker:s.kicker,title:s.title,lead:s.lead,content:s.content,notes:s.notes}});
 const simpleEN={
  'Un récit en quatre mouvements':['Introduction','A four-part narrative','The presentation follows the logic connecting the research question, results, methods and decisions.'],
  'Dix études principales, mais une logique commune':['Thesis project','Ten core studies, one shared logic','The projects explore temporal and spatial variants around a small number of common mechanisms.'],
  'De la fenêtre audiovisuelle à la temporalité olfactive':['Experimental program','From audiovisual binding to olfactory timing','TWIXAV provides the reference from which olfactory binding and sensory timing are investigated.'],
  'Les études futures prolongent des mécanismes déjà testés':['Perspectives','Future studies extend already-tested mechanisms','Prospective projects remain conditional extensions of the core studies.'],
  'Trois prolongements possibles autour de l’extension et de la restriction':['Perspectives','Three possible extensions around extension and restriction','COBEX, BRAUD and BRAUDOLF are conditional spatial extensions.'],
  'FLUXOLF - une branche méthodologique utile, distincte de la thèse':['Side project','FLUXOLF - a useful methodological side project','FLUXOLF supports physiological-method development without becoming a third thesis axis.'],
  'Une plateforme expérimentale commune plutôt qu’un montage par étude':['Methods','A shared experimental platform rather than one setup per study','A common software, hardware and logging architecture supports the different experiments.'],
  'Déclencher sur un événement physiologique, pas seulement logiciel':['Methods','Triggering on a physiological event, not only a software event','Respiratory phase is part of experimental control for olfactory studies.'],
  'Une seule logique de traitement, adaptée à chaque famille de mesures':['Methods','One analysis logic adapted to each family of measures','Behavioral, EEG and physiological pipelines share reproducible principles.'],
  'Des sorties standardisées pour comparer les études':['Methods','Standardized outputs across studies','Behavioral analyses produce reproducible tables, figures and Quarto reports.'],
  'La robustesse du protocole inclut aussi la charge participant':['Methods','Protocol robustness also includes participant burden','Feasibility includes preparation time, comfort, traceability and data protection.'],
  'Des développements logiciels conçus pour réduire la friction de recherche':['Methods','Software developments designed to reduce research friction','Dashboards, inventory and analysis tools directly support data collection and reproducibility.'],
  'Les principales difficultés ont déjà modifié la manière de concevoir les études':['Methods','The main difficulties have already changed study design','Olfactory timing, multiple devices and complex analyses led to methodological changes.'],
  'La première année a aussi construit un profil de chercheur':['Doctoral development','The first year also built a researcher profile','The first year developed scientific, experimental, analytical and tool-building skills.'],
  'Passer de prototypes et prétests à des sorties scientifiques':['Year 2','From prototypes and pretests to scientific outputs','The next step is to convert mature results into analyses, presentations and manuscripts.'],
  'Un horizon court centré sur la consolidation':['Year 2','A short-term horizon focused on consolidation','The next cycle prioritizes core studies before further extensions.'],
  'Une progression conditionnelle plutôt qu’un calendrier rigide':['Year 2','Conditional progression rather than a rigid schedule','Future studies are activated according to results and feasibility.'],
  'Construire progressivement un profil de maître de conférences':['Career','Building an academic teaching-research profile','The career objective combines autonomous research, teaching, methods and collective contribution.'],
  'Une première année passée de la question à l’infrastructure':['Conclusion','A first year moving from the question to the infrastructure','The program is now structured around reference studies, identified technical dependencies and shared tools.'],
  'Glossaire des projets':['Appendix','Project glossary','Compact glossary of project acronyms for questions.'],
  'SOFT - paramètres techniques actuellement prévus':['Appendix','SOFT - current technical parameters','Technical details on durations, orders, ITIs, calibration, EEG triggers and logs.'],
  'Configuration physiologique et EEG':['Appendix','Physiological and EEG configuration','Summary of EEG, EDA, ECG and respiratory acquisition.'],
  'Bibliothèque de stimuli olfactifs envisagée':['Appendix','Candidate olfactory stimulus library','Candidate odorants and diluents considered for experimental pretesting.'],
  'Règles communes du pipeline comportemental':['Appendix','Common behavioral-pipeline rules','Shared preprocessing, aggregation and statistical-analysis rules.']};
 const card=(h,p)=>`<div class="card"><h3>${h}</h3><p>${p}</p></div>`;
 const specificEN=s=>{const t=s._fr.title,b={section:'PhD progress review',kicker:'Progress review',title:t,lead:s._fr.lead,content:s._fr.content,notes:''};
  if(t.includes('espace-temps pour les odeurs'))return {...b,section:'Introduction',kicker:'Individual PhD Monitoring Committee - 1',title:'Is there a space-time for odors?',lead:'Mechanisms of integration between olfaction, vision and audition - first PhD year.',content:s._fr.content.replaceAll('Doctorat en psychologie cognitive','PhD in Cognitive Psychology').replaceAll('Doctorant','PhD candidate').replaceAll('Direction','Supervisor').replaceAll('Co-direction','Co-supervisor').replaceAll('Comité de Suivi Individuel','Individual PhD Monitoring Committee').replaceAll('Maître de conférences en psychologie','Associate Professor in Psychology').replaceAll('Chargée de recherche CNRS','CNRS Research Scientist').replaceAll('psychologie de l’olfaction','olfactory psychology')};
  if(t.includes('Deux axes'))return {...b,section:'Thesis project',kicker:'Research question',title:'Two complementary axes on multisensory space and time',lead:'The thesis asks how olfaction fits into mechanisms usually investigated in vision and audition.',content:`<div class="project-map"><div class="axis-card"><span class="badge">Axis 1</span><h3>Spatiotemporal relations between olfaction, vision and audition</h3><p>When are signals from different sensory modalities processed as the same event?</p></div><div class="axis-card"><span class="badge">Axis 2</span><h3>Influence of odors on auditory and visual spatiotemporal perception</h3><p>Can odors change how visual or auditory events are represented in space and time?</p></div></div>`};
  if(t.includes('TWIXAV -'))return {...b,section:'Experimental program',kicker:'TWIXAV - completed pretest',title:'TWIXAV - an audiovisual reference',lead:'TWIXAV provides an audiovisual baseline before introducing olfactory constraints.',content:s._fr.content.replaceAll('Design','Design').replaceAll('Prétest audiovisuel','Audiovisual pretest').replaceAll('Jugement de simultanéité','Simultaneity judgment').replaceAll('Manipulation du SOA et de la durée','SOA and duration manipulation').replaceAll('Mémoire de M1','M1 thesis').replaceAll('courbes de simultanéité','simultaneity curves').replaceAll('Résultats','Results').replaceAll('Photo de passation / écran participant','Testing / participant-screen photo')};
  if(t.includes('SOFT -'))return {...b,section:'Experimental program',kicker:'SOFT - ready to launch',title:'SOFT - dissociating onset, offset and duration',lead:'SOFT directly tests a possible explanation of the asymmetry observed in TWIXAV.',content:s._fr.content.replaceAll('Prête à démarrer','Ready to launch').replaceAll('Question','Question').replaceAll('Mesures','Measures').replaceAll('onset perçu','perceived onset').replaceAll('offset perçu','perceived offset').replaceAll('durée perçue','perceived duration').replaceAll('EEG et physiologie selon configuration','EEG and peripheral physiology depending on configuration').replaceAll('EEG 128 canaux','128-channel EEG').replaceAll('physiologie','physiology')};
  if(t.includes('Transposer la liaison'))return {...b,section:'Experimental program',kicker:'TWIXOLF - ready to launch',title:'TWIXOLF - transferring temporal binding to olfaction',lead:'TWIXOLF extends the temporal binding window framework to olfaction.',content:s._fr.content.replaceAll('Prête à démarrer','Ready to launch').replaceAll('Variables critiques','Critical variables').replaceAll('État actuel','Current status').replaceAll('Architecture expérimentale et contrôles matériels préparés pour le pilote.','Experimental architecture and hardware controls are prepared for the pilot.').replaceAll('Photo de contexte - installation participant','Context photo - participant setup')};
  if(t.includes('VIBEX -'))return {...b,section:'Experimental program',kicker:'VIBEX - completed pretest',title:'VIBEX - a visual Boundary Extension reference',lead:'VIBEX provides the visual baseline before olfactory or intermodal extensions.',content:s._fr.content.replaceAll('Prétest','Pretest').replaceAll('Manipulation de zoom','Zoom manipulation').replaceAll('Réponse identique / différente','Same / different response').replaceAll('Mémoire de M1','M1 thesis').replaceAll('résultats à intégrer','results to insert').replaceAll('Résultats','Results').replaceAll('Exemple de scène / stimulus','Example scene / stimulus')};
  if(t.includes('OASIS -'))return {...b,section:'Experimental program',kicker:'OASIS - ready to launch',title:'OASIS - odor, approach-avoidance and space',lead:'OASIS examines how olfactory presence interacts with spatial approach and avoidance responses.',content:s._fr.content.replaceAll('Prête à démarrer','Ready to launch').replaceAll('Dimension cognitive','Cognitive dimension').replaceAll('Mesures','Measures').replaceAll('État actuel','Current status').replaceAll('Photo de contexte - préparation olfactive','Context photo - olfactory preparation')};
  if(t.includes('Enseignements réalisés'))return {...b,section:'Doctoral development',kicker:'Teaching - 2025-2026',title:'Teaching completed during the first year',lead:'Completed teaching covers experimental methodology, undergraduate research supervision and a practical neuroscience class.',content:s._fr.content.replaceAll('équivalent TD valorisé en 2025-2026, complété par 6 h de TP Master non comptabilisées dans ce total.','tutorial-equivalent hours credited in 2025-2026, plus a 6-hour Master practical class not included in this total.').replaceAll('Méthodologie Expérimentale en Psychologie Cognitive','Experimental Methodology in Cognitive Psychology').replaceAll('Comprendre les Interactions entre les Sens','Understanding Interactions Between the Senses').replaceAll('Signatures cardiaques et électrodermales des émotions.','Cardiac and electrodermal signatures of emotions.')};
  if(t.includes('Formations suivies'))return {...b,section:'Doctoral development',kicker:'Doctoral training - 2025-2026',title:'Training completed during the first year',lead:'The doctoral training program combined university pedagogy, career development, research integrity, documentation and valorization.',content:s._fr.content.replaceAll('Poursuite de carrière - Enseignement','Career development - Teaching').replaceAll('Apprendre à enseigner à l’université - niveau 1','Learning to teach at university - level 1').replaceAll('IA et Éducation','AI and Education').replaceAll('Introduction à l’intelligence économique','Introduction to economic intelligence').replaceAll('Intégrité scientifique et déontologie','Scientific integrity and professional ethics').replaceAll('Zotero - gérer ses références bibliographiques','Zotero - managing bibliographic references')};
  if(t.includes('Rétroplanning'))return {...b,section:'Year 2',kicker:'2026-2027 timeline',title:'Timeline for the core studies',lead:'The operational sequence is SOFT, then OASIS, then TWIXOLF, while analyses and writing proceed in parallel.',content:s._fr.content.replaceAll('Sept-Oct','Sep-Oct').replaceAll('Oct-Déc','Oct-Dec').replaceAll('Jan-Mars','Jan-Mar').replaceAll('Avr-Juin','Apr-Jun').replaceAll('En parallèle','In parallel').replaceAll('Analyses finales et valorisation.','Final analyses and dissemination.').replaceAll('Uniquement selon résultats et faisabilité.','Only if supported by results and feasibility.')};
  if(t.includes('Enseignements prévus'))return {...b,section:'Year 2',kicker:'Teaching - 2026-2027',title:'Teaching planned for the second year',lead:'The planned 2026-2027 teaching program spans all three undergraduate years and totals 58 tutorial-equivalent hours.',content:s._fr.content.replaceAll('Méthodologie Expérimentale en Psychologie Cognitive','Experimental Methodology in Cognitive Psychology').replaceAll('UE2 Psychologie Cognitive - partie attention','UE2 Cognitive Psychology - attention').replaceAll('Comprendre les Interactions entre les Sens','Understanding Interactions Between the Senses')};
  if(t.includes('Formations envisagées'))return {...b,section:'Year 2',kicker:'Doctoral training - 2026-2027',title:'Training priorities for the second year',lead:'Second-year training will be selected according to PhD needs and the academic career project.',content:s._fr.content.replaceAll('Pédagogie','Pedagogy').replaceAll('Enseignement universitaire','University teaching').replaceAll('Méthodes','Methods').replaceAll('Analyse et reproductibilité','Analysis and reproducibility').replaceAll('Carrière','Career').replaceAll('Préparation au métier d’enseignant-chercheur','Preparation for an academic teaching-research career').replaceAll('Priorité','Priority').replaceAll('Selon offre','Depending on available courses')};
  if(t.includes('Communications envisagées'))return {...b,section:'Year 2',kicker:'Outreach and communication',title:'Planned outreach and communication in 2026-2027',lead:'Outreach activities are positioned after the scientific, experimental and methodological core of the PhD.',content:s._fr.content.replaceAll('Nuit des chercheurs','Researchers’ Night').replaceAll('Septembre','September').replaceAll('Fête de la Science','Science Festival').replaceAll('Octobre','October').replaceAll('Mars','March').replaceAll('Juin','June')};
  if(t.includes('Merci pour votre attention'))return {...b,section:'Acknowledgements',kicker:'Acknowledgements',title:'Thank you for your attention',lead:'Thanks to the Individual PhD Monitoring Committee and the supervisory team for their feedback and continued support.',content:s._fr.content.replaceAll('Comité de Suivi Individuel','Individual PhD Monitoring Committee').replaceAll('Maître de conférences en psychologie','Associate Professor in Psychology').replaceAll('Chargée de recherche CNRS','CNRS Research Scientist').replaceAll('Direction de thèse','PhD supervision').replaceAll('directeur de thèse','supervisor').replaceAll('co-directeur de thèse','co-supervisor')};
  if(t.includes('Repères bibliographiques'))return {...b,section:'References',kicker:'Main references',title:t.replace('Repères bibliographiques','Selected references'),lead:'Key references used in the theoretical framework.',content:s._fr.content};
  const e=simpleEN[t];if(e)return {...b,section:e[0],kicker:e[0],title:e[1],lead:e[2],content:`<div class="grid two">${card('Purpose',e[2])}${card('Key point','This information is integrated into the overall thesis narrative and can be expanded during discussion if needed.')}</div>`};
  return {...b,section:s.appendix?'Appendix':'PhD progress review',kicker:s.appendix?'Appendix':'Progress review',title:'PhD progress - '+t,lead:'English version for international presentations.',content:`<div class="grid two">${card('Purpose','This slide presents the corresponding scientific, methodological or doctoral-development point in English.')}${card('Discussion','Detailed technical information can be provided during questions.')}</div>`};};
 const notesEN=()=>`<div class="csi-note-block"><strong>Core message</strong><br>State the main scientific or doctoral-development point shown on this slide.</div><div class="csi-note-block"><strong>What to emphasize</strong><br>• Keep the argument focused.<br>• Connect the slide to the previous one.<br>• Keep non-essential technical details for questions.</div><div class="csi-note-block"><strong>Transition</strong><br>Move directly to the next step of the narrative.</div>`;
 slides.forEach(s=>{s._en=specificEN(s);s._en.notes=notesEN()});
 let lang=localStorage.getItem('csi-lang')||'fr';const actions=d.querySelector('.app-actions');if(actions&&!d.getElementById('csiLang')){const sw=d.createElement('div');sw.id='csiLang';sw.className='csi-lang';sw.innerHTML='<button type="button" data-lang="fr">FR</button><button type="button" data-lang="en">EN</button>';actions.insertBefore(sw,actions.firstChild)}
 const activeIndex=()=>Number(d.querySelector('.slide.active')?.dataset.index||0);const T={fr:{mode:'Mode diapo',nav:'Sommaire',ov:'Vue d’ensemble',notes:'Notes orateur',fs:'Plein écran',settings:'Personnalisation',search:'Rechercher une slide...'},en:{mode:'Slide mode',nav:'Contents',ov:'Overview',notes:'Speaker notes',fs:'Full screen',settings:'Settings',search:'Search slides...'}};
 const paintNotes=()=>{const body=d.getElementById('notesBody');if(!body)return;const i=activeIndex(),s=slides[i]||slides[0],next=slides.slice(i+1).find(x=>lang==='en'||!x.appendix);body.innerHTML=`<div class="csi-note-title">${s.title}</div>${s.notes||''}${next?`<div class="csi-note-next"><strong>${lang==='en'?'Next':'Suivante'} :</strong> ${next.title}</div>`:''}`};
 const applyLang=L=>{const i=activeIndex();lang=L;localStorage.setItem('csi-lang',L);d.documentElement.lang=L;slides.forEach(s=>{const v=L==='en'?s._en:s._fr;s.section=v.section;s.kicker=v.kicker;s.title=v.title;s.lead=v.lead;s.content=v.content;s.notes=v.notes});d.querySelectorAll('#csiLang button').forEach(b=>b.classList.toggle('active',b.dataset.lang===L));if(typeof w.renderSlides==='function')w.renderSlides();if(typeof w.goTo==='function')w.goTo(i,false);const x=T[L],set=(id,title)=>{const e=d.getElementById(id);if(e){e.title=title;e.setAttribute('aria-label',title)}};set('navBtn',x.nav);set('overviewBtn',x.ov);set('notesBtn',x.notes);set('fullscreenBtn',x.fs);set('settingsBtn',x.settings);const q=d.getElementById('navSearch');if(q)q.placeholder=x.search;paintNotes()};d.querySelectorAll('#csiLang button').forEach(b=>b.addEventListener('click',()=>applyLang(b.dataset.lang)));
 const np=d.getElementById('notesPanel');if(np){np.classList.add('csi-notes');const saved=JSON.parse(localStorage.getItem('csi-notes-pos')||'null');if(saved){np.style.setProperty('left',saved.left+'px','important');np.style.setProperty('top',saved.top+'px','important');np.style.setProperty('width',saved.width+'px','important');np.style.setProperty('height',saved.height+'px','important')}const h=np.querySelector('.panel-head');let drag=null;h.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;const r=np.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:r.left,top:r.top};h.setPointerCapture(e.pointerId)});h.addEventListener('pointermove',e=>{if(!drag)return;const l=Math.max(0,Math.min(innerWidth-np.offsetWidth,drag.left+e.clientX-drag.x)),t=Math.max(0,Math.min(innerHeight-60,drag.top+e.clientY-drag.y));np.style.setProperty('left',l+'px','important');np.style.setProperty('top',t+'px','important')});const end=()=>{if(!drag)return;drag=null;const r=np.getBoundingClientRect();localStorage.setItem('csi-notes-pos',JSON.stringify({left:r.left,top:r.top,width:r.width,height:r.height}))};h.addEventListener('pointerup',end);h.addEventListener('pointercancel',end)}
 const baseUpdate=w.updateUI;if(typeof baseUpdate==='function')w.updateUI=function(){baseUpdate.apply(this,arguments);paintNotes()};
 if(actions&&!d.getElementById('csiQBtn')){const b=d.createElement('button');b.className='icon-btn';b.id='csiQBtn';b.type='button';b.textContent='Q';b.title='Questions spécifiques';actions.insertBefore(b,d.getElementById('settingsBtn'));const v=d.createElement('section');v.id='csiQVault';v.innerHTML='<div class="csi-q-inner"><div class="csi-q-head"><div><div class="slide-kicker">Slides cachées</div><h2 style="font-family:Georgia,serif;font-size:clamp(2.5rem,5vw,5rem);margin:.3em 0 0">Questions spécifiques</h2></div><button class="csi-q-close">Retour</button></div><div class="csi-q-blank"></div></div>';d.body.appendChild(v);b.onclick=()=>v.style.display='block';v.querySelector('.csi-q-close').onclick=()=>v.style.display='none'}
 if(typeof w.renderSlides==='function')w.renderSlides();if(typeof w.goTo==='function')w.goTo(0,false);applyLang(lang);
 d.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(d.activeElement?.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();e.stopImmediatePropagation();if(typeof w.move==='function')w.move(1);paintNotes();return}if(e.key==='ArrowLeft'){e.preventDefault();e.stopImmediatePropagation();if(typeof w.move==='function')w.move(-1);paintNotes();return}const blocked=[' ','Home','End','PageDown','PageUp','m','M','o','O','n','N','f','F','c','C'];if(blocked.includes(e.key)){e.preventDefault();e.stopImmediatePropagation()}},true);
}catch(e){console.error('CSI11 ui',e)}});})();