(function(){
const frame=document.getElementById('presentation');if(!frame)return;
frame.addEventListener('load',()=>{try{
 const w=frame.contentWindow,d=w.document,C=w.CSI11;if(!C)return;const slides=C.slides;
 const by=t=>slides.find(s=>s._fr&&s._fr.title&&s._fr.title.includes(t));
 const lang=()=>localStorage.getItem('csi-lang')||'fr';
 const css=`
 .csi-logo-cloud{background:transparent!important;box-shadow:none!important;padding:0!important;gap:10px!important;max-width:1120px!important}.csi-logo-cloud img{box-sizing:border-box!important;max-width:165px!important;max-height:62px!important;padding:9px 12px!important;border-radius:16px!important;background:rgba(255,255,255,.94)!important;border:1px solid rgba(255,255,255,.55)!important;box-shadow:0 8px 20px rgba(0,0,0,.1)!important}.csi-logo-cloud img.wide{max-width:210px!important}
 .csi-people-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.csi-person{min-height:285px;border:1px solid var(--line);border-radius:24px;background:var(--white);padding:12px;box-shadow:0 12px 30px color-mix(in srgb,var(--accent-strong) 10%,transparent)}.csi-person.primary{background:linear-gradient(145deg,var(--hero-mid),var(--hero-start));color:#fff}.csi-person.primary h3,.csi-person.primary p,.csi-person.primary .role{color:#fff!important}.csi-photo{height:126px;border-radius:17px;border:1px dashed var(--line);background:linear-gradient(135deg,var(--accent-pale),var(--white));display:grid;place-items:center;color:var(--muted);font-weight:900;font-size:.75rem;text-transform:uppercase}.csi-person.primary .csi-photo{background:rgba(255,255,255,.1);border-color:rgba(255,255,255,.25);color:rgba(255,255,255,.75)}.csi-person h3{font:800 1.08rem Georgia,serif;color:var(--accent-strong);margin:12px 3px 5px}.csi-person p{margin:0 3px;color:var(--muted);font-size:.78rem;line-height:1.4}.role{display:inline-flex;margin:8px 3px 0;padding:5px 8px;border-radius:999px;background:var(--accent-pale);color:var(--accent-strong);font-size:.65rem;font-weight:950;text-transform:uppercase}
 .csi-m1{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.csi-m1 article{border:1px solid var(--line);border-radius:25px;background:var(--white);padding:13px;box-shadow:0 12px 30px color-mix(in srgb,var(--accent-strong) 9%,transparent)}.csi-m1 .pic{height:160px;border:1px dashed var(--line);border-radius:18px;background:linear-gradient(135deg,var(--accent-pale),var(--white));display:grid;place-items:center;color:var(--muted);font-weight:900}.csi-m1 h3{margin:12px 4px 3px;color:var(--accent-strong);font:800 1.22rem Georgia,serif}.csi-m1 p{margin:0 4px;color:var(--muted);font-size:.84rem;line-height:1.42}.proj{display:inline-flex;margin:8px 4px 2px;padding:5px 9px;border-radius:999px;background:var(--accent-soft);color:var(--accent-strong);font-weight:950;font-size:.69rem}
 .csi-axis2{display:grid;grid-template-columns:minmax(0,1fr) 250px;gap:18px;align-items:start}.csi-collab{border:1px solid var(--line);border-radius:24px;background:var(--white);padding:9px;box-shadow:0 16px 38px color-mix(in srgb,var(--accent-strong) 15%,transparent);transform:rotate(.7deg)}.csi-collab img{width:100%;height:132px;object-fit:cover;border-radius:15px}.csi-collab img.logo{height:52px;object-fit:contain;margin-top:5px}.csi-collab strong{display:block;color:var(--accent-strong);font:800 .98rem Georgia,serif;margin:8px 6px 3px}.csi-collab p{margin:0 6px 7px;color:var(--muted);font-size:.74rem;line-height:1.4}
 .refs{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:11px!important}.refs p{margin:0!important;padding:13px 15px!important;border:1px solid var(--line)!important;border-radius:17px!important;background:var(--white)!important;box-shadow:0 7px 19px color-mix(in srgb,var(--accent-strong) 7%,transparent)!important;font-size:.74rem!important;line-height:1.42!important;color:var(--muted)!important;overflow-wrap:anywhere}
 .csi-decisions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.csi-decision{display:grid;grid-template-columns:40px 1fr;gap:10px;padding:13px 15px;border:1px solid var(--line);border-radius:19px;background:var(--white);box-shadow:0 8px 22px color-mix(in srgb,var(--accent-strong) 8%,transparent)}.csi-decision b{display:grid;place-items:center;width:36px;height:36px;border-radius:12px;background:var(--accent);color:#fff}.csi-decision h3{margin:1px 0 3px;color:var(--accent-strong);font:800 .94rem Georgia,serif}.csi-decision p{margin:0;color:var(--muted);font-size:.76rem;line-height:1.34}.slide:has(.csi-decisions){padding-top:86px!important;padding-bottom:70px!important}.slide:has(.csi-decisions) .lead{margin-bottom:15px!important}
 #notesPanel{display:none!important}.csi-vigilance{background:color-mix(in srgb,var(--accent-pale) 65%,#fff1d7)!important}
 @media(max-width:1250px){.csi-people-grid{grid-template-columns:repeat(3,1fr)}.csi-axis2{grid-template-columns:1fr 220px}.refs{grid-template-columns:1fr!important}}@media(max-width:850px){.csi-people-grid,.csi-m1,.csi-decisions{grid-template-columns:1fr}.csi-axis2{grid-template-columns:1fr}.csi-collab{max-width:360px;transform:none}}
 `;const st=d.createElement('style');st.textContent=css;d.head.appendChild(st);
 const note=(core,pts=[],watch='',trans='')=>`<div class="csi-note-block"><strong>Message central</strong><br>${core}</div><div class="csi-note-block"><strong>À dire</strong><br>${pts.map(x=>'• '+x).join('<br>')}</div>${watch?`<div class="csi-note-block csi-vigilance"><strong>À surveiller</strong><br>${watch}</div>`:''}${trans?`<div class="csi-note-block"><strong>Transition</strong><br>${trans}</div>`:''}`;
 const person=(n,r,p,primary=false)=>`<article class="csi-person${primary?' primary':''}"><div class="csi-photo">Photo</div><span class="role">${r}</span><h3>${n}</h3><p>${p}</p></article>`;
 const collabFR=`<aside class="csi-collab"><img src="https://laboratoire-psychologie.univ-fcomte.fr/wp-content/uploads/2022/03/Besancon_boucle_Doubs-reduit.jpg" alt="Besançon"><img class="logo" src="https://laboratoire-psychologie.umlp.fr/wp-content/uploads/2023/12/cropped-Logo-Laboratoire-de-Psychologie-296x82.jpg" alt="Laboratoire de Psychologie"><strong>Collaboration - Besançon</strong><p>Laboratoire de Psychologie - Université Marie et Louis Pasteur. Appui scientifique sur les paradigmes de représentation des scènes et de Boundary Extension.</p></aside>`;
 const collabEN=collabFR.replace('Appui scientifique sur les paradigmes de représentation des scènes et de Boundary Extension.','Scientific exchange around scene representation and Boundary Extension paradigms.');
 const biopac='https://sensorlab.arizona.edu/sites/default/files/styles/az_card_image/public/2023-06/biopac.jpg.webp?itok=KDhaWerq',cynexo='https://www.cynexo.com/wp-content/uploads/2018/09/sniff-O-foto5.jpg';
 const replacePhoto=(html,label,url)=>html.replace(`<figure class="csi-float-photo"><div class="csi-photo-placeholder">Photo</div><figcaption>${label}</figcaption></figure>`,`<figure class="csi-float-photo"><img src="${url}" alt="${label}"><figcaption>${label}</figcaption></figure>`);
 let s=by('Un environnement qui combine');if(s){s._fr.title='Encadrement, équipe et Comité de Suivi Individuel';s._fr.lead='Le projet doctoral s’inscrit au CSGA, dans l’équipe DOCC, avec un encadrement scientifique et un suivi individuel clairement identifiés.';s._fr.content=`<div class="csi-people-grid">${person('Luc PERROQUIN','Doctorant','Psychologie cognitive - CSGA, équipe DOCC.',true)}${person('Renaud BROCHARD','Direction','Professeur des Universités - directeur de thèse.')}${person('Arnaud LELEU','Co-direction','Maître de conférences - co-directeur de thèse.')}${person('Fabrice Damon','CSI','Maître de conférences en psychologie - Université Bourgogne Europe, CSGA - DOCC.')}${person('Camille Ferdenzi-Lemaître','CSI','Chargée de recherche CNRS - Centre de Recherche en Neurosciences de Lyon.')}</div>`;s._fr.notes=note('Présenter les personnes qui structurent l’environnement scientifique et le suivi de la thèse.',['Situer le CSGA et l’équipe DOCC.','Nommer la direction de thèse.','Présenter les deux membres du CSI.'],'Rester bref sur les biographies.','Passer aux deux axes de recherche.');if(s._en){s._en.title='Supervision, team and Individual PhD Monitoring Committee';s._en.content=s._fr.content.replace('Doctorant','PhD candidate').replace('Direction','Supervisor').replace('Co-direction','Co-supervisor').replaceAll('Maître de conférences','Associate Professor').replace('Chargée de recherche CNRS','CNRS Research Scientist')}}
 s=by('Enseignement et formation - bilan de première année');if(s){s._fr.content=s._fr.content.replace('<div class="big-number" style="color:#fff">60 h</div>','<div class="big-number" style="color:#fff">54 h</div>');s._fr.notes=note('Le bilan d’enseignement doit être présenté avec le bon total.',['54 h équivalent TD valorisé en 2025-2026.','6 h de TP Master affichées séparément et exclues du total.','60 h de formation doctorale.'],'Ne jamais annoncer 60 h équivalent TD pour l’enseignement.','Détailler enseignement puis formation.');if(s._en)s._en.content=s._en.content.replace('60 h','54 h')}
 s=by('Enseignements réalisés en première année');if(s){s._fr.lead='Le volume d’enseignement valorisé en 2025-2026 est de 54 h équivalent TD. Les 6 h de TP Master apparaissent séparément et ne sont pas intégrées à ce total.';s._fr.content=s._fr.content.replace('<div class="big-number">60 h</div>','<div class="big-number">54 h</div>').replace('équivalent TD valorisé en 2025-2026, complété par 6 h de TP Master non comptabilisées dans ce total.','équivalent TD valorisé en 2025-2026. Les 6 h de TP Master sont présentées séparément et ne sont pas comptabilisées dans ce total.');s._fr.notes=note('Présenter le volume d’enseignement sans ambiguïté.',['40 h eq. TD en L1.','14 h eq. TD de TER en L3.','6 h de TP Master affichées mais hors total.'],'Total à annoncer : 54 h eq. TD.','Passer aux formations suivies.');if(s._en)s._en.content=s._en.content.replace('<div class="big-number">60 h</div>','<div class="big-number">54 h</div>')}
 s=by('SOFT -');if(s){s._fr.content=replacePhoto(s._fr.content,'BIOPAC MP160 - physiologie',biopac);s._fr.notes=note('SOFT teste si l’asymétrie temporelle peut être reliée à une précision différente du début et de la fin perceptifs.',['Comparer onset, offset et durée perçus dans les trois modalités.','BioSemi et BIOPAC sont montrés ici parce qu’ils appartiennent à la chaîne de mesure envisagée.','Le pilote doit tester charge de session, triggers et synchronisation.'],'EEG et physiologie restent conditionnés par la faisabilité du pilote.','Passer à TWIXOLF.')}
 s=by('Transposer la liaison temporelle');if(s){s._fr.content=s._fr.content.replace('<figure class="csi-float-photo"><div class="csi-photo-placeholder">Photo</div><figcaption>Photo de contexte - installation participant</figcaption></figure>','');s._fr.notes=note('TWIXOLF transpose la fenêtre temporelle à l’olfaction.',['Distinguer commande, délivrance, inspiration et perception.','Le CyNexo intervient directement dans cette manipulation.','Dans le calendrier de collecte, OASIS passe avant TWIXOLF.'],'Ne pas confondre ordre conceptuel et ordre de collecte.','Passer à l’Axe 2.')}
 s=by('TWIXAV -');if(s){s._fr.content=s._fr.content.replace('<div class="callout" style="margin-top:14px"><strong>Mémoire de M1 :</strong> Alicia.</div>','');s._fr.notes=note('TWIXAV fournit la référence audiovisuelle de l’Axe 1 et motive SOFT.',['Rappeler jugement de simultanéité, SOA et durée.','Commenter courbes, PSS, largeur et asymétrie une fois les figures finales intégrées.','Le M1 d’Alicia est regroupé plus tard avec les autres encadrements.'],'Conserver une interprétation prudente car il s’agit d’un prétest.','Passer aux résultats puis à SOFT.')}
 s=by('VIBEX -');if(s){s._fr.content=s._fr.content.replace('<div class="callout" style="margin-top:14px"><strong>Mémoire de M1 :</strong> Olivia.</div>','');s._fr.content=`<div class="csi-axis2"><div>${s._fr.content}</div>${collabFR}</div>`;s._fr.notes=note('VIBEX établit la référence visuelle de Boundary Extension.',['Présenter le paradigme sans répéter tout le cadre théorique.','Signaler la collaboration avec le Laboratoire de Psychologie à Besançon.','Le M1 d’Olivia est regroupé plus tard avec les autres encadrements.'],'Ne pas surcharger la slide de détails analytiques.','Passer à OASIS.');if(s._en)s._en.content=`<div class="csi-axis2"><div>${s._en.content}</div>${collabEN}</div>`}
 s=by('OASIS -');if(s){s._fr.content=replacePhoto(s._fr.content,'BIOPAC - EDA / ECG',biopac);s._fr.content=replacePhoto(s._fr.content,'Photo de contexte - préparation olfactive',cynexo).replace('Photo de contexte - préparation olfactive','CyNexo Sniff-0 - stimulation olfactive');s._fr.content=`<div class="csi-axis2"><div>${s._fr.content}</div>${collabFR}</div>`;s._fr.notes=note('OASIS est la collecte olfactive spatiale prioritaire avant TWIXOLF.',['Relier l’odeur aux réponses spatiales d’approche-évitement.','Montrer CyNexo et BIOPAC sur cette slide car ils sont directement mobilisés.','Présenter la collaboration de Besançon comme appui scientifique.'],'EDA/ECG ne sont pas des marqueurs univoques d’un état psychologique.','Rappeler dans le rétroplanning qu’OASIS précède TWIXOLF.');if(s._en)s._en.content=`<div class="csi-axis2"><div>${s._en.content}</div>${collabEN}</div>`}
 const skills=by('La première année a aussi construit');if(skills&&!slides.some(x=>x._fr&&x._fr.title==='Encadrement de mémoires de Master 1')){const m={section:'Développement doctoral',kicker:'Encadrement - Master 1',title:'Encadrement de mémoires de Master 1',lead:'Trois mémoires de M1 ont été articulés à des projets expérimentaux ou méthodologiques du programme.',content:`<div class="csi-m1"><article><div class="pic">Photo</div><span class="proj">TWIXAV</span><h3>Alicia</h3><p>Fenêtre temporelle d’intégration audiovisuelle, jugement de simultanéité et asymétrie temporelle.</p></article><article><div class="pic">Photo</div><span class="proj">VIBEX</span><h3>Olivia Hiridjee</h3><p>Influence de la taille des images sur la Boundary Extension et consolidation du paradigme visuel de l’Axe 2.</p></article><article><div class="pic">Photo</div><span class="proj">FLUXOLF</span><h3>Morgane Barret</h3><p>Projet annexe mobilisant olfaction et mesures physiologiques, utile pour consolider les méthodes du doctorat.</p></article></div>`,notes:note('Présenter l’encadrement comme une composante du profil d’enseignant-chercheur.',['Alicia : TWIXAV.','Olivia Hiridjee : VIBEX.','Morgane Barret : FLUXOLF.'],'Ne pas attribuer aux mémoires des conclusions non établies.','Passer au bilan enseignement et formation.')};m._fr={section:m.section,kicker:m.kicker,title:m.title,lead:m.lead,content:m.content,notes:m.notes};m._en={section:'Doctoral development',kicker:'Supervision - Master 1',title:'Master 1 research supervision',lead:'Three M1 projects were connected to experimental or methodological components of the PhD.',content:m.content,notes:m.notes};slides.splice(slides.indexOf(skills)+1,0,m)}
 ['Repères bibliographiques - Axe 1','Repères bibliographiques - Axe 2'].forEach(k=>{const r=by(k);if(r)r._fr.notes=note('Utiliser cette diapositive comme appui bibliographique.',['Les références sont formatées de façon lisible et cohérente avec APA.','Pointer uniquement les travaux directement liés à la question.','Distinguer références fondatrices et travaux récents.'],'Ne pas lire la bibliographie à l’oral.','Revenir à la discussion.')});
 s=by('Rétroplanning des études centrales');if(s)s._fr.notes=note('Le calendrier suit désormais une séquence opérationnelle claire.',['SOFT en premier.','OASIS avant TWIXOLF.','TWIXAV et VIBEX : analyses et rédaction en parallèle.'],'Les extensions restent conditionnelles.','Passer aux autres composantes de l’année 2.');
 s=by('Les décisions les plus utiles')||by('Les arbitrages les plus utiles');if(s){const c=(n,h,p)=>`<article class="csi-decision"><b>${n}</b><div><h3>${h}</h3><p>${p}</p></div></article>`;s._fr.kicker='09 - Décisions à discuter';s._fr.title='Les arbitrages les plus utiles à obtenir du comité';s._fr.lead='Le CSI peut surtout aider à sécuriser les choix qui conditionnent la faisabilité de l’année 2.';s._fr.content=`<div class="csi-decisions">${c(1,'Ordre des manipulations','Valider SOFT -> OASIS -> TWIXOLF et les chevauchements acceptables de collecte/analyse.')}${c(2,'Périmètre de SOFT','Arbitrer la durée maximale de session, la place de l’EEG/physiologie et les critères de simplification.')}${c(3,'Matériel','Sécuriser le matériel dédié, les solutions de secours et la fiabilité du poste expérimental.')}${c(4,'Valorisation','Prioriser VIBEX puis TWIXAV et définir le niveau de maturité nécessaire avant soumission.')}${c(5,'Extensions','Définir les critères qui justifieraient SORBET, SOLAR, COBEX, BRAUD ou BRAUDOLF.')}${c(6,'Charge doctorale','Maintenir une articulation réaliste entre collectes, analyses, écriture, enseignement, formation et diffusion.')}</div>`;s._fr.notes=note('Ouvrir une vraie discussion et obtenir des arbitrages actionnables.',['Valider l’ordre SOFT -> OASIS -> TWIXOLF.','Définir comment simplifier SOFT si nécessaire.','Discuter le niveau de résultats requis avant valorisation.','Confirmer que les extensions restent conditionnelles.'],'Éviter de refaire un résumé complet de la présentation.','Conclure ensuite sans ajouter de nouvelles perspectives.');if(s._en){s._en.title='The most useful decisions to obtain from the committee';s._en.content=s._fr.content}}
 s=by('Merci pour votre attention');if(s){s._fr.lead='Merci aux membres du Comité de Suivi Individuel et à la direction de thèse pour leurs retours et leur accompagnement.';s._fr.content=`<div class="csi-people-grid" style="grid-template-columns:repeat(4,minmax(0,1fr))">${person('Fabrice Damon','CSI','Maître de conférences en psychologie - UBE, CSGA - DOCC.')}${person('Camille Ferdenzi-Lemaître','CSI','Chargée de recherche CNRS - CRNL.')}${person('Renaud BROCHARD','Direction','Professeur des Universités - directeur de thèse.')}${person('Arnaud LELEU','Co-direction','Maître de conférences - co-directeur de thèse.')}</div>`;s._fr.notes=note('Clore sans nouvelle information.',['Remercier le CSI et la direction.','Rester sur cette slide pendant les échanges.'],'Ne pas rouvrir les perspectives.','')}
 const notesBtn=d.getElementById('notesBtn');let nw=null;const idx=()=>Number(d.querySelector('.slide.active')?.dataset.index||0);const payload=()=>{const i=idx(),x=slides[i]||slides[0],n=slides[i+1];return{type:'csi-notes-v12',index:i,total:slides.length,title:x?.title||'',section:x?.section||'',notes:x?.notes||'',nextTitle:n?.title||'',lang:lang(),ts:Date.now()}};const send=()=>{const p=payload();try{localStorage.setItem('csi-notes-v12-last',JSON.stringify(p))}catch(e){}try{const ch=new BroadcastChannel('csi-notes-v12');ch.postMessage(p);ch.close()}catch(e){}try{if(nw&&!nw.closed)nw.postMessage(p,location.origin)}catch(e){}};if(notesBtn){notesBtn.title='Notes orateur - fenêtre séparée';notesBtn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();nw=window.open('notes.html','csiSpeakerNotes','popup=yes,width=760,height=900,resizable=yes,scrollbars=yes');setTimeout(send,180)},true)}let last='';setInterval(()=>{const p=payload(),k=p.index+'|'+p.title+'|'+p.lang;if(k!==last){last=k;send()}},250);window.addEventListener('message',e=>{if(e.origin===location.origin&&e.data==='csi-notes-v12-ready')send()});
 const L=lang();slides.forEach(x=>{const v=L==='en'?x._en:x._fr;if(v){x.section=v.section;x.kicker=v.kicker;x.title=v.title;x.lead=v.lead;x.content=v.content;x.notes=v.notes}});if(typeof w.renderSlides==='function')w.renderSlides();if(typeof w.goTo==='function')w.goTo(0,false);send();
}catch(e){console.error('CSI V12',e)}});
})();
