(function(){
const frame=document.getElementById('presentation');
if(!frame)return;
frame.addEventListener('load',()=>{
 try{
  const w=frame.contentWindow,d=w.document,slides=w.eval('slides');
  const find=t=>slides.find(s=>s.title&&s.title.includes(t));
  const refs=t=>`<div class="csi-ref"><strong>Références :</strong> ${t}</div>`;
  const css=`
  .slide{overflow-y:auto!important;scrollbar-width:none;padding-bottom:max(var(--slide-pad-y),110px)!important}.slide::-webkit-scrollbar{display:none}.slide .slide-shell{align-self:flex-start;width:min(var(--page-width),100%);margin:auto}.slide-content{align-content:start}.slide h2{font-size:clamp(2rem,4.05vw,4.4rem)!important;line-height:1!important}
  .csi-ref{margin-top:14px;padding-top:8px;border-top:1px solid var(--line);font-size:.72rem;color:var(--muted)}.csi-ref strong{color:var(--accent-strong)}
  .csi-logos{margin-top:18px;background:#fff;border-radius:20px;padding:10px 14px;display:grid;grid-template-columns:1.5fr .7fr 1.1fr .85fr;gap:14px;align-items:center;max-width:800px;box-shadow:0 10px 26px rgba(0,0,0,.12)}.csi-logos img{width:100%;height:62px;object-fit:contain}.csi-logo-word{height:62px;display:grid;place-items:center;font-weight:950;color:#173f5f;border-left:1px solid #e5e5e5}
  .csi-members{margin-top:14px;padding:12px 15px;border:1px solid rgba(255,255,255,.22);border-radius:18px;background:rgba(255,255,255,.09)}.csi-members strong{display:block;margin-top:5px}
  .csi-devices{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.csi-device{border:1px solid var(--line);border-radius:26px;background:var(--white);box-shadow:var(--shadow-soft);overflow:hidden}.csi-media{height:215px;background:#fff;border-bottom:1px solid var(--line);display:grid;place-items:center;overflow:hidden}.csi-media img,.csi-media iframe{width:100%;height:100%;object-fit:contain;border:0}.csi-device-copy{padding:18px}.csi-device-copy h3{margin:0 0 8px}.csi-device-copy p{margin:0;color:var(--muted);font-size:.91rem}
  .csi-retro{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}.csi-retro>div{border:1px solid var(--line);border-radius:20px;background:var(--white);padding:16px;box-shadow:var(--shadow-soft)}.csi-retro h3{margin:9px 0 5px;font-size:1.03rem}.csi-retro p{font-size:.81rem;color:var(--muted);margin:0}.csi-date{font-size:.7rem;text-transform:uppercase;letter-spacing:.07em;color:var(--accent);font-weight:950}
  .question-list{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:11px!important}.question-list .question{padding:14px 16px!important;min-height:0!important}.question-list .question strong{color:var(--accent-strong)}
  #csiQVault{position:fixed;inset:0;z-index:3000;background:linear-gradient(180deg,var(--cream),var(--accent-pale));display:none;overflow:auto;color:var(--text)}.csi-q-inner{width:min(1480px,100%);min-height:100vh;margin:auto;padding:96px clamp(28px,5vw,84px) 70px}.csi-q-head{display:flex;justify-content:space-between;align-items:center;gap:18px}.csi-q-close{border:1px solid var(--line);background:var(--white);color:var(--text);border-radius:999px;padding:10px 15px;font-weight:900;cursor:pointer}.csi-q-blank{margin-top:34px;min-height:55vh;border:1px dashed var(--line);border-radius:34px;background:var(--white);display:grid;place-items:center;text-align:center;color:var(--muted);padding:30px}
  @media(max-width:1100px){.csi-devices{grid-template-columns:1fr}.csi-retro{grid-template-columns:repeat(2,1fr)}.question-list{grid-template-columns:1fr!important}.csi-logos{grid-template-columns:repeat(2,1fr)}}`;
  const st=d.createElement('style');st.textContent=css;d.head.appendChild(st);

  const cover=find("Y a-t-il un espace-temps pour les odeurs ?");
  if(cover){cover.hero=true;cover.content=`<div><span class="eyebrow">Doctorat en psychologie cognitive · CSI-1</span><h1>Y a-t-il un espace-temps pour les odeurs&nbsp;?</h1><p class="subtitle">Mécanismes d'intégration entre olfaction, vision et audition</p><div class="csi-logos"><img src="https://til.u-bourgogne.fr/wp-content/uploads/2025/01/logo-UBE-drapeau-quadri.jpg" alt="Université Bourgogne Europe"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Cnrs-logo.svg" alt="CNRS"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Logo%20Institut%20Agro%202022.png" alt="Institut Agro"><div class="csi-logo-word">INRAE</div></div></div><aside class="identity-card"><div class="mono">Doctorant</div><strong>Luc PERROQUIN</strong><div class="identity-list"><div class="identity-row"><div class="mono">Direction</div><strong>Renaud BROCHARD</strong><br>Professeur des Universités - directeur</div><div class="identity-row"><div class="mono">Co-direction</div><strong>Arnaud LELEU</strong><br>Maître de conférences</div><div class="identity-row"><div class="mono">Équipe</div><strong>DOCC - CSGA</strong><br>Université Bourgogne Europe</div></div><div class="csi-members"><div class="mono">Comité de Suivi Individuel</div><strong>Fabrice Damon</strong><strong>Camille Ferdenzi-Lemaître</strong></div></aside>`;}

  const time=find("Le temps multisensoriel");if(time)time.content+=refs("Vroomen & Keetels, 2010 ; Keetels & Vroomen, 2012 ; Powers et al., 2009 ; Stevenson et al., 2012 ; Stein & Stanford, 2008.");
  const olf=find("L'olfaction complique le problème temporel");if(olf)olf.content+=refs("Gotow & Kobayakawa, 2017 ; Mainland & Sobel, 2006 ; Sela & Sobel, 2010.");
  const scene=find("La perception de scène dépasse parfois les frontières visibles");if(scene)scene.content+=refs("Intraub & Richardson, 1989 ; Intraub, 2012 ; Gagnier et al., 2013 ; Bainbridge & Baker, 2020 ; Park et al., 2024.");

  const soft=find("Mesurer le temps propre de chaque modalité");if(soft){soft.title="SOFT - dissocier onset, offset et durée";soft.lead="SOFT teste directement une explication possible de l'asymétrie observée avec TWIXAV.";soft.content+=refs("Vroomen & Keetels, 2010 ; Keetels & Vroomen, 2012 ; Powers et al., 2009.");}
  const oasis=find("OASIS - relier odeur, approche-évitement et espace");if(oasis){oasis.kicker="OASIS - prochaine collecte";oasis.lead="OASIS est planifiée avant TWIXOLF dans le rétroplanning 2026-2027.";oasis.content+=refs("Rekow et al., 2022 ; Hörberg et al., 2020 ; Gottfried, 2010.");}
  const twixolf=find("Transposer la liaison temporelle à l'olfaction");if(twixolf){twixolf.kicker="TWIXOLF - après OASIS";twixolf.lead="TWIXOLF reste l'étude centrale de transposition olfactive de l'Axe 1, mais elle est programmée après OASIS dans la séquence opérationnelle.";twixolf.content+=refs("Gotow & Kobayakawa, 2017 ; Keetels & Vroomen, 2012 ; Sela & Sobel, 2010.");}

  const hardware={section:"Infrastructure",kicker:"Appareillage",title:"Une chaîne instrumentale multimodale",lead:"Les appareils sont présentés comme une chaîne unique de stimulation, synchronisation et acquisition.",content:`<div class="csi-devices"><article class="csi-device"><div class="csi-media"><iframe title="CyNexo Sniff-0" src="https://www.cynexo.com/wp-content/uploads/2020/10/Sniff-0-Product-Data-Sheet-REV201016.pdf#page=1&toolbar=0&navpanes=0"></iframe></div><div class="csi-device-copy"><h3>CyNexo Sniff-0</h3><p>Olfactomètre utilisé pour contrôler la délivrance odorante et la synchronisation avec les événements expérimentaux et respiratoires.</p></div></article><article class="csi-device"><div class="csi-media"><img src="https://www.biosemi.com/pics/cap_128_layout_medium.jpg" alt="BioSemi ActiveTwo EEG"></div><div class="csi-device-copy"><h3>BioSemi ActiveTwo</h3><p>Système EEG mobilisé pour l'acquisition électrophysiologique et le marquage temporel des événements.</p></div></article><article class="csi-device"><div class="csi-media"><iframe title="BIOPAC MP160" src="https://www.biopac.com/wp-content/uploads/MP160-Systems.pdf#page=1&toolbar=0&navpanes=0"></iframe></div><div class="csi-device-copy"><h3>BIOPAC MP160</h3><p>Plateforme d'acquisition physiologique pour EDA, ECG, EMG/SKT et voies complémentaires selon le protocole.</p></div></article></div>${refs("Documentation constructeur CyNexo Sniff-0 ; BioSemi ActiveTwo ; BIOPAC MP160.")}`};

  const difficulties=find("Les principales difficultés ont déjà modifié la manière de concevoir les études");if(difficulties){difficulties.section="Infrastructure";difficulties.kicker="Difficultés expérimentales";difficulties.lead="Ces contraintes sont présentées avant le calendrier futur, car elles déterminent directement la faisabilité des études suivantes.";}

  const comm=find("Rendre la recherche visible, compréhensible et recrutante");if(comm){comm.section="Suite";comm.kicker="Communications envisagées";comm.title="Une programmation de diffusion étalée sur l'année";comm.lead="Le calendrier de communication reste lié à la maturité réelle des résultats.";comm.content=`<div class="timeline"><div class="timeline-item"><div class="timeline-dot">09</div><h3>Nuit des chercheurs</h3><p>Septembre 2026</p></div><div class="timeline-item"><div class="timeline-dot">10</div><h3>Fête de la Science</h3><p>Octobre 2026</p></div><div class="timeline-item"><div class="timeline-dot">03</div><h3>Expérimentarium</h3><p>Mars 2027</p></div><div class="timeline-item"><div class="timeline-dot">06</div><h3>FJC</h3><p>Juin 2027</p></div><div class="timeline-item"><div class="timeline-dot">06</div><h3>JDD</h3><p>Juin 2027</p></div></div><div class="bridge">Adapter le contenu présenté à la maturité des données disponibles à chaque échéance.</div>`;}

  const retro={section:"Suite",kicker:"Rétroplanning 2026-2027",title:"OASIS avant TWIXOLF",lead:"L'ordre opérationnel retenu suit la faisabilité : SOFT d'abord, puis OASIS, puis TWIXOLF.",content:`<div class="csi-retro"><div><div class="csi-date">Sept-Oct 2026</div><h3>SOFT - pilote</h3><p>Charge participant, onset/offset, triggers et matériel.</p></div><div><div class="csi-date">Oct-Déc 2026</div><h3>SOFT - collecte</h3><p>Collecte prioritaire et analyses intermédiaires.</p></div><div><div class="csi-date">Jan-Mars 2027</div><h3>OASIS</h3><p>Prétests odorants/physio puis collecte spatiale.</p></div><div><div class="csi-date">Avr-Juin 2027</div><h3>TWIXOLF</h3><p>Prétests puis collecte temporelle olfactive.</p></div><div><div class="csi-date">En parallèle</div><h3>TWIXAV + VIBEX</h3><p>Analyses finales et rédaction.</p></div><div><div class="csi-date">2027-2028</div><h3>Extensions</h3><p>Uniquement selon résultats et faisabilité.</p></div></div><div class="callout" style="margin-top:16px"><strong>Règle :</strong> analyse et rédaction avancent pendant les collectes suivantes.</div>`};

  const prod=find("Passer de prototypes et prétests à des sorties scientifiques");if(prod){prod.section="Suite";prod.kicker="Productions scientifiques";}
  const future=find("Une progression conditionnelle plutôt qu'un calendrier rigide");if(future){future.section="Perspectives";future.kicker="Extensions conditionnelles";future.title="Étendre seulement après consolidation";future.lead="Les projets exploratoires viennent après les études centrales, les difficultés et le rétroplanning.";}
  const decisions=find("Les décisions les plus utiles à discuter aujourd'hui");if(decisions){decisions.kicker="Décisions à discuter";decisions.lead="Le CSI peut aider à sécuriser les choix qui conditionnent la faisabilité de l'année 2.";decisions.content=`<div class="question-list"><div class="question"><strong>Ordre des manipulations</strong><br>Valider SOFT → OASIS → TWIXOLF et le niveau acceptable de chevauchement collecte/analyse.</div><div class="question"><strong>Périmètre de SOFT</strong><br>Durée de session, place de l'EEG/physiologie et critères de simplification si le pilote est trop lourd.</div><div class="question"><strong>Matériel</strong><br>Identifier les éléments à sécuriser pour limiter panne et incompatibilité.</div><div class="question"><strong>Valorisation</strong><br>Prioriser le short paper VIBEX puis TWIXAV selon la solidité des analyses.</div><div class="question"><strong>Extensions</strong><br>Définir les critères qui justifieraient SORBET, SOLAR, COBEX, BRAUD ou BRAUDOLF.</div><div class="question"><strong>Charge doctorale</strong><br>Préserver l'équilibre entre collectes, enseignement, formations et communications.</div></div>`;}

  const thanks={section:"Remerciements",kicker:"Remerciements",title:"Merci pour votre suivi et vos échanges",lead:"Cette première année a bénéficié d'un encadrement scientifique régulier et du regard extérieur du Comité de Suivi Individuel.",content:`<div class="grid two"><div class="card dark"><h3>Comité de Suivi Individuel</h3><p><strong>Fabrice Damon</strong></p><p style="margin-top:10px"><strong>Camille Ferdenzi-Lemaître</strong></p><p style="margin-top:18px">Merci pour votre lecture, vos retours et les échanges consacrés à la trajectoire du projet.</p></div><div class="card"><h3>Direction de thèse</h3><p><strong>Renaud Brochard</strong> - directeur</p><p style="margin-top:10px"><strong>Arnaud Leleu</strong> - co-directeur</p><div class="csi-logos"><img src="https://til.u-bourgogne.fr/wp-content/uploads/2025/01/logo-UBE-drapeau-quadri.jpg" alt="Université Bourgogne Europe"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Cnrs-logo.svg" alt="CNRS"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Logo%20Institut%20Agro%202022.png" alt="Institut Agro"><div class="csi-logo-word">INRAE</div></div></div></div>`};
  const conclusion=find("Une première année passée de la question à l'infrastructure");if(conclusion){conclusion.content=`<div class="grid three"><div class="card dark"><h3>Acquis</h3><p>TWIXAV et VIBEX fournissent deux références comportementales et l'infrastructure multimodale est structurée.</p></div><div class="card"><h3>Ordre 2026-2027</h3><p>SOFT → OASIS → TWIXOLF, avec analyse et rédaction conduites en parallèle.</p></div><div class="card"><h3>Principe</h3><p>Étendre le programme uniquement après consolidation des études centrales.</p></div></div>`;}

  const normal=slides.filter(s=>!s.appendix);
  const pick=t=>normal.find(s=>s.title&&s.title.includes(t));
  const intro=normal.slice(0,2);
  const ordered=[...intro,pick("D'un parcours généraliste"),pick("Un environnement qui combine"),pick("Deux axes pour interroger"),pick("L'intégration multisensorielle"),time,olf,scene,pick("TWIXAV - établir"),pick("Un effet net"),soft,pick("VIBEX - établir"),oasis,twixolf,pick("Ce qui est déjà acquis"),pick("La première année a aussi construit"),find("Un développement doctoral"),find("Des développements logiciels"),hardware,difficulties,comm,retro,prod,future,decisions,thanks,conclusion,find("Repères bibliographiques - Axe 1"),find("Repères bibliographiques - Axe 2")].filter(Boolean);
  const seen=new Set();const deck=[];ordered.forEach(s=>{if(!seen.has(s)){seen.add(s);deck.push(s);}});
  slides.splice(0,slides.length,...deck);
  w.renderSlides();w.goTo(0,false);

  const actions=d.querySelector('.app-actions');
  if(actions&&!d.getElementById('csiQBtn')){const b=d.createElement('button');b.className='icon-btn';b.id='csiQBtn';b.type='button';b.textContent='Q';b.title='Questions spécifiques';actions.insertBefore(b,d.getElementById('settingsBtn'));const v=d.createElement('section');v.id='csiQVault';v.innerHTML=`<div class="csi-q-inner"><div class="csi-q-head"><div><div class="slide-kicker">Slides cachées</div><h2 style="font-family:Georgia,serif;font-size:clamp(2.5rem,5vw,5rem);margin:.3em 0 0">Questions spécifiques</h2></div><button class="csi-q-close">Retour</button></div><div class="csi-q-blank"><div><strong>Page réservée</strong><br>Aucune réponse spécifique n'est préparée pour le moment.<br>Les futures diapositives de réponse seront ajoutées ici sans apparaître dans le fil principal.</div></div></div>`;d.body.appendChild(v);b.onclick=()=>v.style.display='block';v.querySelector('.csi-q-close').onclick=()=>v.style.display='none';}
 }catch(e){console.error('CSI v9',e);}
});
})();
