(function(){
const frame=document.getElementById('presentation');if(!frame)return;
frame.addEventListener('load',()=>setTimeout(()=>{try{
const w=frame.contentWindow,d=w.document,C=w.CSI11;if(!C||!C.slides)return;const slides=C.slides;
const by=t=>slides.find(s=>((s._fr&&s._fr.title)||s.title||'').includes(t));
const fr=s=>s&&s._fr?s._fr:s;const set=(s,k,v)=>{if(!s)return;(s._fr||s)[k]=v};
const refs=t=>`<div class="csi-v14-refs"><strong>Références</strong><span>${t}</span></div>`;
const css=`
.csi-person{min-height:345px!important;display:flex!important;flex-direction:column!important}.csi-photo{height:174px!important;min-height:174px!important;padding:0!important;overflow:hidden!important;border-style:solid!important}.csi-photo img{width:100%!important;height:100%!important;object-fit:cover!important;object-position:center 16%!important;border-radius:16px!important}.csi-person .role{background:var(--accent-soft)!important;color:var(--accent-strong)!important;border:1px solid color-mix(in srgb,var(--accent) 22%,transparent)!important}.csi-person.primary .role{background:#dcefe5!important;color:#123a2d!important;border-color:rgba(18,58,45,.16)!important}
.csi-hardware-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.csi-hw{border:1px solid var(--line);border-radius:24px;background:var(--white);padding:12px;box-shadow:0 12px 30px color-mix(in srgb,var(--accent-strong) 10%,transparent)}.csi-hw .pic{height:185px;border-radius:18px;overflow:hidden;background:#fff;border:1px solid var(--line)}.csi-hw img{width:100%;height:100%;object-fit:contain;display:block}.csi-hw .tag{display:inline-flex;margin:11px 3px 0;padding:5px 9px;border-radius:999px;background:var(--accent-soft);color:var(--accent-strong);font-size:.66rem;font-weight:950;text-transform:uppercase}.csi-hw h3{margin:8px 3px 5px;color:var(--accent-strong);font:800 1.08rem Georgia,serif}.csi-hw p,.csi-hw li{color:var(--muted);font-size:.76rem;line-height:1.4}.csi-hw p{margin:0 3px}.csi-hw ul{margin:7px 0 0 20px;padding:0}
.slide:has(.csi-v14-decisions){overflow-y:auto!important;padding-top:82px!important;padding-bottom:160px!important;scroll-padding-bottom:150px!important}.slide:has(.csi-v14-decisions) .slide-shell{padding-bottom:90px!important}.slide:has(.csi-v14-decisions) .lead{margin-bottom:12px!important}.csi-v14-decisions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 12px}.csi-v14-decision{display:grid;grid-template-columns:38px 1fr;gap:10px;padding:11px 13px;border:1px solid var(--line);border-radius:18px;background:var(--white);box-shadow:0 7px 20px color-mix(in srgb,var(--accent-strong) 7%,transparent)}.csi-v14-decision b{display:grid;place-items:center;width:36px;height:36px;border-radius:12px;background:var(--accent);color:#fff}.csi-v14-decision h3{margin:0 0 3px;color:var(--accent-strong);font:800 .92rem Georgia,serif}.csi-v14-decision p{margin:0;color:var(--muted);font-size:.72rem;line-height:1.3}
.csi-v14-thanks{display:grid;grid-template-columns:.8fr 1.2fr;gap:20px}.csi-v14-thanks .message{border-radius:28px;padding:26px;background:linear-gradient(145deg,var(--hero-mid),var(--hero-start));color:#fff;display:flex;flex-direction:column;justify-content:center}.csi-v14-thanks .message h3{font:800 2rem Georgia,serif;margin:0 0 9px;color:#fff}.csi-v14-thanks .message p{margin:0;color:rgba(255,255,255,.82)}.csi-v14-members{display:grid;grid-template-columns:1fr 1fr;gap:13px}.csi-v14-member{border:1px solid var(--line);border-radius:23px;background:var(--white);padding:19px;box-shadow:0 10px 28px color-mix(in srgb,var(--accent-strong) 9%,transparent)}.csi-v14-member .i{width:46px;height:46px;border-radius:14px;background:var(--accent);color:#fff;display:grid;place-items:center;font-weight:950;margin-bottom:12px}.csi-v14-member h3{margin:0 0 4px;color:var(--accent-strong);font:800 1.12rem Georgia,serif}.csi-v14-member p{margin:0;color:var(--muted);font-size:.8rem}.csi-v14-direction{grid-column:1/-1;border:1px dashed var(--line);border-radius:17px;padding:12px 14px;background:var(--accent-pale);color:var(--muted);font-size:.78rem}
.csi-v14-refs{margin-top:11px;padding-top:8px;border-top:1px solid var(--line);display:flex;gap:9px;font-size:.67rem;line-height:1.38;color:var(--muted)}.csi-v14-refs strong{color:var(--accent-strong);flex:0 0 auto}#csiQuestionsBtn{min-width:36px!important;padding:7px 10px!important;font-weight:950!important}
@media(max-width:1150px){.csi-hardware-grid{grid-template-columns:1fr 1fr}.csi-v14-thanks{grid-template-columns:1fr}}@media(max-width:820px){.csi-hardware-grid,.csi-v14-decisions,.csi-v14-members{grid-template-columns:1fr}.csi-v14-direction{grid-column:auto}.slide:has(.csi-v14-decisions){padding-bottom:180px!important}}@media(max-height:790px) and (min-width:821px){.slide:has(.csi-v14-decisions) h2{font-size:clamp(2rem,3.2vw,3.3rem)!important}.csi-v14-decision{padding:8px 11px}.csi-v14-decision p{font-size:.68rem}}
`;
const st=d.createElement('style');st.id='csiV14';st.textContent=css;d.head.appendChild(st);

/* Portraits direction/doctorant, avec cadrage plus haut. */
const portraits={'Luc PERROQUIN':'https://raw.githubusercontent.com/lucper01/Portfolio/main/assets/photo-profil.png','Renaud BROCHARD':'https://raw.githubusercontent.com/lucper01/Portfolio/main/assets/renaud.jpg','Arnaud LELEU':'https://raw.githubusercontent.com/lucper01/Portfolio/main/assets/arnaud.jpg'};
function injectPortraits(){d.querySelectorAll('.csi-person h3').forEach(h=>{const src=portraits[h.textContent.trim()];if(!src)return;const slot=h.closest('.csi-person')?.querySelector('.csi-photo');if(slot&&!slot.querySelector('img'))slot.innerHTML=`<img src="${src}" alt="${h.textContent.trim()}">`;});}

/* Matériel illustré dans des cartes. */
const hw=by('Une plateforme expérimentale')||by('plateforme expérimentale');if(hw){set(hw,'kicker','Méthodologie - instrumentation');set(hw,'title','Une plateforme multimodale articulant olfactométrie, EEG et physiologie');set(hw,'lead','Les dispositifs sont regroupés afin de rendre explicite la chaîne instrumentale et les contraintes de synchronisation propres aux protocoles multisensoriels.');set(hw,'content',`<div class="csi-hardware-grid"><article class="csi-hw"><div class="pic"><img src="https://www.cynexo.com/wp-content/uploads/2018/09/sniff-O-foto5.jpg" alt="CyNexo Sniff-0"></div><span class="tag">Olfactométrie</span><h3>CyNexo Sniff-0 / Spir-0</h3><p>Administration contrôlée des odeurs et synchronisation sur le cycle respiratoire.</p><ul><li>débit, valves et flush</li><li>déclenchement sur inspiration</li><li>logs des délais de stimulation</li></ul></article><article class="csi-hw"><div class="pic"><img src="https://www.biosemi.com/pics/cap_128_medium1_large.jpg" alt="BioSemi ActiveTwo"></div><span class="tag">EEG</span><h3>BioSemi ActiveTwo</h3><p>Acquisition EEG haute densité lorsque la dynamique électrophysiologique est informative.</p><ul><li>128 canaux + références</li><li>marqueurs synchronisés</li><li>contrôle du timing et des artefacts</li></ul></article><article class="csi-hw"><div class="pic"><img src="https://sensorlab.arizona.edu/sites/default/files/styles/az_card_image/public/2023-06/biopac.jpg.webp?itok=KDhaWerq" alt="BIOPAC MP160"></div><span class="tag">Psychophysiologie</span><h3>BIOPAC / BioNomadix</h3><p>Mesures autonomes et périphériques complémentaires au comportement.</p><ul><li>EDA, ECG, EMG et SKT</li><li>AcqKnowledge</li><li>marqueurs TTL</li></ul></article></div>${refs('Mainland & Sobel, 2006 ; Zelano et al., 2016 ; Luck, 2014 ; Boucsein, 2012 ; Shaffer & Ginsberg, 2017.')}`);}

/* Rétroplanning : OASIS avant TWIXOLF. */
const retro=by('Rétroplanning des études centrales');if(retro){set(retro,'lead','La séquence opérationnelle retenue est SOFT, puis OASIS, puis TWIXOLF, tandis que TWIXAV et VIBEX avancent en parallèle sur l’analyse et la valorisation.');set(retro,'content',`<div class="csi-retro"><div><div class="csi-date">Sept-Oct 2026</div><h3>SOFT - pilote</h3><p>Validation de la passation, du timing, des triggers et de la charge participant.</p></div><div><div class="csi-date">Oct-Déc 2026</div><h3>SOFT - collecte</h3><p>Collecte prioritaire et analyses intermédiaires.</p></div><div><div class="csi-date">Jan-Mars 2027</div><h3>OASIS</h3><p>Pilote puis collecte spatiale olfactive.</p></div><div><div class="csi-date">Avr-Juin 2027</div><h3>TWIXOLF</h3><p>Pilote puis collecte temporelle olfactive.</p></div><div><div class="csi-date">En parallèle</div><h3>TWIXAV + VIBEX</h3><p>Analyses finales, figures, rédaction et valorisation.</p></div><div><div class="csi-date">2027-2028</div><h3>Extensions</h3><p>Uniquement selon résultats et faisabilité.</p></div></div>`);}

/* Communications prévues. */
const comm=by('Communications envisagées');if(comm){set(comm,'lead','Les actions de diffusion sont placées après le calendrier expérimental afin de conserver une progression chronologique : contraintes, collectes, analyses, puis valorisation.');set(comm,'content',`<div class="csi-diffusion"><div class="csi-diff"><div class="dot">09</div><h3>Nuit des chercheurs</h3><p>Septembre 2026</p></div><div class="csi-diff"><div class="dot">10</div><h3>Fête de la Science</h3><p>Octobre 2026</p></div><div class="csi-diff"><div class="dot">03</div><h3>Expérimentarium</h3><p>Mars 2027</p></div><div class="csi-diff"><div class="dot">06</div><h3>FJC</h3><p>Juin 2027</p></div><div class="csi-diff"><div class="dot">06</div><h3>JDD</h3><p>Juin 2027</p></div></div>`);}

/* Arbitrages : 2 colonnes pour éviter tout débordement hors plein écran. */
const dec=by('Les arbitrages les plus utiles')||by('Les décisions les plus utiles');if(dec){const item=(n,t,p)=>`<article class="csi-v14-decision"><b>${n}</b><div><h3>${t}</h3><p>${p}</p></div></article>`;set(dec,'lead','Le CSI peut surtout aider à sécuriser les choix qui conditionnent la faisabilité de l’année 2.');set(dec,'content',`<div class="csi-v14-decisions">${item(1,'Ordre des manipulations','Valider SOFT -> OASIS -> TWIXOLF et préciser jusqu’où accepter les chevauchements entre collecte, analyse et rédaction.')}${item(2,'Périmètre de SOFT','Fixer la durée maximale de session, la place de l’EEG/physiologie et les critères de simplification si le pilote est trop lourd.')}${item(3,'Matériel','Sécuriser le matériel dédié, les solutions de secours et l’éventuelle évolution du PC expérimental.')}${item(4,'Valorisation','Prioriser le short paper VIBEX puis TWIXAV et définir le niveau de résultat requis avant soumission ou communication.')}${item(5,'Extensions','Définir les critères déclenchant SORBET, SOLAR, COBEX, BRAUD ou BRAUDOLF plutôt que de les maintenir automatiquement dans le noyau de thèse.')}${item(6,'Charge doctorale','Maintenir un calendrier soutenable entre collectes, analyses, enseignements, formations, encadrements et diffusion.')}</div>`);}

/* Références supplémentaires. */
function addRef(t,x){const s=by(t);if(!s)return;const o=fr(s);if(o.content&&!o.content.includes('csi-v14-refs'))set(s,'content',o.content+refs(x));}
addRef("L'olfaction complique le problème temporel",'Mainland & Sobel, 2006 ; Gotow & Kobayakawa, 2017 ; Zelano et al., 2016.');addRef('TWIXAV -','Powers et al., 2009 ; Vroomen & Keetels, 2010 ; Stevenson et al., 2012 ; Keetels & Vroomen, 2012.');addRef('SOFT -','Vroomen & Keetels, 2010 ; Stevenson et al., 2012 ; Mainland & Sobel, 2006.');addRef('Transposer la liaison temporelle','Gotow & Kobayakawa, 2017 ; Mainland & Sobel, 2006 ; Sela & Sobel, 2010.');addRef('VIBEX -','Intraub & Richardson, 1989 ; Intraub, 2012 ; Bainbridge & Baker, 2020 ; Park et al., 2024.');addRef('OASIS -','Hörberg et al., 2020 ; Rekow et al., 2022 ; Intraub, 2012.');addRef('Les principales difficultés','Boucsein, 2012 ; Shaffer & Ginsberg, 2017 ; Luck, 2014.');

/* Remerciements avec membres du CSI. */
const thanks=by('Merci pour votre attention');if(thanks){set(thanks,'kicker','Remerciements');set(thanks,'lead','Merci aux membres du Comité de Suivi Individuel pour leur lecture, leurs remarques et les arbitrages proposés sur la suite du doctorat.');set(thanks,'content',`<div class="csi-v14-thanks"><div class="message"><h3>Merci</h3><p>Les échanges du CSI doivent permettre de consolider la faisabilité de l’année 2 tout en maintenant la cohérence scientifique du programme STOLF.</p></div><div class="csi-v14-members"><article class="csi-v14-member"><div class="i">FD</div><h3>Fabrice Damon</h3><p>Maître de conférences en psychologie - Université Bourgogne Europe, CSGA - équipe DOCC.</p></article><article class="csi-v14-member"><div class="i">CF</div><h3>Camille Ferdenzi-Lemaître</h3><p>Chargée de recherche CNRS - Centre de Recherche en Neurosciences de Lyon.</p></article><div class="csi-v14-direction"><strong>Direction :</strong> Renaud Brochard - directeur de thèse ; Arnaud Leleu - co-directeur de thèse.</div></div></div>`);}

/* Difficultés avant perspectives, quelle que soit une réorganisation antérieure. */
const diff=by('Les principales difficultés');if(diff&&retro){const a=slides.indexOf(diff),b=slides.indexOf(retro);if(a>b){slides.splice(a,1);slides.splice(b,0,diff);}}

/* Bouton vers la réserve de slides cachées. */
function qbtn(){const actions=d.querySelector('.app-actions');if(!actions||d.getElementById('csiQuestionsBtn'))return;const b=d.createElement('button');b.id='csiQuestionsBtn';b.className='icon-btn';b.type='button';b.title='Questions spécifiques';b.setAttribute('aria-label','Questions spécifiques');b.textContent='?';b.onclick=()=>{try{window.top.location.href='questions.html'}catch(e){window.location.href='questions.html'}};actions.insertBefore(b,actions.firstChild);}

const lang=localStorage.getItem('csi-lang')||'fr';slides.forEach(s=>{const v=lang==='en'?s._en:s._fr;if(v){s.section=v.section;s.kicker=v.kicker;s.title=v.title;s.lead=v.lead;s.content=v.content;s.notes=v.notes}});
const base=w.renderSlides;if(typeof base==='function'&&!w.__v14){w.__v14=true;w.renderSlides=function(){base.apply(this,arguments);qbtn();setTimeout(injectPortraits,0)}}
if(typeof w.renderSlides==='function')w.renderSlides();qbtn();injectPortraits();const ver=d.getElementById('csiVersion');if(ver)ver.textContent='V14 - 03/09';
}catch(e){console.error('CSI V14',e)}},180));
})();