(function(){
const VERSION='V13 - 03/09';
const frame=document.getElementById('presentation');if(!frame)return;
function onReady(fn){
  const run=()=>{try{fn()}catch(e){console.error('CSI V13',e)}};
  frame.addEventListener('load',()=>setTimeout(run,80));
  try{if(frame.contentDocument&&frame.contentDocument.readyState!=='loading')setTimeout(run,120)}catch(e){}
}
onReady(()=>{
 const w=frame.contentWindow,d=w.document,C=w.CSI11;if(!C||!C.slides)return;const slides=C.slides;
 const find=t=>slides.find(s=>s._fr&&s._fr.title&&s._fr.title.includes(t));
 const css=`
  body[data-view="slides"] .deck{perspective:1600px;overflow:hidden}.slide{will-change:opacity,transform}.slide.active .slide-shell{animation:csiFadeUp .34s cubic-bezier(.22,.61,.36,1) both}body[data-csi-dir="prev"] .slide.active .slide-shell{animation-name:csiFadeDown}@keyframes csiFadeUp{from{opacity:0;transform:translateY(18px) scale(.985)}to{opacity:1;transform:translateY(0) scale(1)}}@keyframes csiFadeDown{from{opacity:0;transform:translateY(-18px) scale(.985)}to{opacity:1;transform:translateY(0) scale(1)}}body.reduced-motion .slide.active .slide-shell{animation:none!important}
  .appbar{transition:transform .25s ease,box-shadow .25s ease,background .25s ease}.icon-btn,.pill-btn,.slide-link,.overview-card,.card,.csi-person,.csi-decision,.csi-retro>div{transition:transform .18s ease,box-shadow .18s ease,background .18s ease,color .18s ease}.icon-btn:hover,.pill-btn:hover{transform:translateY(-1px)}.slide-link:hover,.overview-card:hover,.card:hover,.csi-person:hover,.csi-decision:hover,.csi-retro>div:hover{transform:translateY(-2px)}
  #csiVersion{display:inline-flex;align-items:center;gap:6px;padding:6px 9px;border-radius:999px;background:var(--accent-soft);color:var(--accent-strong);font-size:.68rem;font-weight:950;letter-spacing:.04em;text-transform:uppercase;white-space:nowrap}#csiVersion::before{content:"";width:7px;height:7px;border-radius:999px;background:var(--accent)}
  #csiChapterBar{position:fixed;z-index:1195;left:50%;top:66px;transform:translateX(-50%);width:min(1180px,calc(100vw - 34px));display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:6px;pointer-events:none}.csi-chap{height:5px;border-radius:999px;background:color-mix(in srgb,var(--accent-soft) 60%,transparent);overflow:hidden}.csi-chap span{display:block;height:100%;width:0;background:var(--accent);border-radius:999px;transition:width .25s ease}.csi-chap.active span{width:100%}.csi-chap.past span{width:100%;opacity:.55}
  .csi-section-pill{display:inline-flex;align-items:center;gap:7px;margin-left:10px;padding:4px 8px;border-radius:999px;background:color-mix(in srgb,var(--accent-soft) 70%,transparent);color:var(--accent-strong);font-size:.62rem;font-weight:950;letter-spacing:.05em;text-transform:uppercase}.csi-section-pill b{width:6px;height:6px;border-radius:99px;background:var(--accent);display:inline-block}
  .csi-transition-card{margin-top:20px;display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:center}.csi-transition-card .box{border:1px solid var(--line);background:var(--white);border-radius:22px;padding:18px;box-shadow:0 8px 22px color-mix(in srgb,var(--accent-strong) 8%,transparent)}.csi-transition-card .arrow{font-size:2rem;font-weight:950;color:var(--accent)}
  .csi-roadline{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.csi-roadline article{border:1px solid var(--line);border-radius:20px;background:var(--white);padding:16px;box-shadow:0 8px 24px color-mix(in srgb,var(--accent-strong) 7%,transparent)}.csi-roadline .num{display:inline-grid;place-items:center;width:34px;height:34px;border-radius:12px;background:var(--accent);color:#fff;font-weight:950;margin-bottom:9px}.csi-roadline h3{margin:0 0 4px;color:var(--accent-strong);font:800 1.02rem Georgia,serif}.csi-roadline p{margin:0;color:var(--muted);font-size:.78rem;line-height:1.4}
  .csi-study-grid,.csi-context,.csi-axis2{align-items:stretch}.csi-float-photo img{background:#fff}.csi-result-slot{transition:min-height .2s ease}.slide h2{max-width:1320px!important}.lead{max-width:1260px!important}
  @media(max-width:1050px){#csiChapterBar{display:none}.csi-roadline{grid-template-columns:repeat(2,1fr)}}@media(max-width:720px){.csi-roadline,.csi-transition-card{grid-template-columns:1fr}.csi-transition-card .arrow{transform:rotate(90deg)}}
 `;const st=d.createElement('style');st.textContent=css;d.head.appendChild(st);
 function chapterFor(s){const t=s.title||'',sec=s.section||'';if(t.includes('espace-temps')||sec==='Introduction'||sec==='Parcours')return 0;if(t.includes('TWIXAV')||t.includes('SOFT')||t.includes('TWIXOLF')||t.includes('audiovisuelle')||t.includes('liaison temporelle')||sec.includes('Programme'))return 1;if(t.includes('VIBEX')||t.includes('OASIS')||t.includes('FLUXOLF')||t.includes('Boundary')||t.includes('études futures')||t.includes('prolongements'))return 2;if(t.includes('plateforme')||t.includes('physiologique')||t.includes('traitement')||t.includes('sorties')||t.includes('robustesse')||t.includes('logiciels')||t.includes('difficultés')||sec==='Méthodologie')return 3;if(t.includes('Enseign')||t.includes('Formation')||t.includes('Master 1')||t.includes('chercheur')||sec.includes('Développement'))return 4;return 5}
 function addChrome(){
  const actions=d.querySelector('.app-actions');if(actions&&!d.getElementById('csiVersion')){const v=d.createElement('span');v.id='csiVersion';v.textContent=VERSION;actions.insertBefore(v,actions.firstChild)}
  if(!d.getElementById('csiChapterBar')){const b=d.createElement('div');b.id='csiChapterBar';b.innerHTML='<div class="csi-chap"><span></span></div><div class="csi-chap"><span></span></div><div class="csi-chap"><span></span></div><div class="csi-chap"><span></span></div><div class="csi-chap"><span></span></div><div class="csi-chap"><span></span></div>';d.body.appendChild(b)}
  d.querySelectorAll('.slide:not(.hero-slide) .slide-kicker').forEach(k=>{if(!k.querySelector('.csi-section-pill')){const i=Number(k.closest('.slide')?.dataset.index||0);const labs=['Intro','Axe 1','Axe 2','Méthodes','Doctorat','Discussion'];k.insertAdjacentHTML('beforeend',`<span class="csi-section-pill"><b></b>${labs[chapterFor(slides[i])]}</span>`)}})
 }
 function paintChapter(){const cur=Number(d.querySelector('.slide.active')?.dataset.index||0),ch=chapterFor(slides[cur]||{});d.querySelectorAll('#csiChapterBar .csi-chap').forEach((e,i)=>{e.classList.toggle('past',i<ch);e.classList.toggle('active',i===ch)})}
 function note(core,pts=[],watch='',trans=''){return `<div class="csi-note-block"><strong>Message central</strong><br>${core}</div><div class="csi-note-block"><strong>À dire</strong><br>${pts.map(x=>'• '+x).join('<br>')}</div>${watch?`<div class="csi-note-block csi-vigilance"><strong>Point de vigilance</strong><br>${watch}</div>`:''}${trans?`<div class="csi-note-block"><strong>Transition</strong><br>${trans}</div>`:''}`}
 const road=find('Un récit en quatre mouvements');if(road){road._fr.content=`<div class="csi-roadline"><article><span class="num">1</span><h3>Installer la question</h3><p>Parcours, environnement, CSI, deux axes et verrou temporel de l’olfaction.</p></article><article><span class="num">2</span><h3>Montrer les études centrales</h3><p>Référence audiovisuelle, SOFT, temporalité olfactive, puis Axe 2 spatial.</p></article><article><span class="num">3</span><h3>Sécuriser la faisabilité</h3><p>Matériel, respiration, mesures, analyses, charge participant et difficultés.</p></article><article><span class="num">4</span><h3>Décider la suite</h3><p>Bilan doctoral, calendrier 2026-2027, valorisation, diffusion et arbitrages.</p></article></div>`;road._fr.notes=note('Annoncer explicitement la logique linéaire de la présentation.',['On ne revient plus en arrière : théorie -> études -> faisabilité -> année 2 -> arbitrages.','Cette slide sert de contrat de lecture pour le CSI.'],'Ne pas détailler les projets ici.','Passer au parcours puis à l’environnement doctoral.')}
 const bridge=find('De la fenêtre audiovisuelle');if(bridge){bridge._fr.content=`<div class="csi-transition-card"><div class="box"><h3>TWIXAV</h3><p>Une référence audiovisuelle met en évidence une fenêtre temporelle modulée par la durée et une asymétrie des réponses.</p></div><div class="arrow">→</div><div class="box"><h3>SOFT puis TWIXOLF</h3><p>SOFT teste l’origine perceptive possible de l’asymétrie, puis TWIXOLF transpose la question à l’olfaction.</p></div></div><div class="bridge">Cette transition évite de traiter TWIXOLF comme une simple réplication : l’étude dépend d’abord du verrou méthodologique mis en évidence par SOFT.</div>`;bridge._fr.notes=note('Faire comprendre pourquoi SOFT est placé avant TWIXOLF dans le récit.',['TWIXAV pose le problème.','SOFT teste le mécanisme possible.','TWIXOLF applique ensuite ce raisonnement à l’olfaction.'],'Ne pas anticiper le rétroplanning ici.','Passer à SOFT.')}
 const dif=find('Les principales difficultés');if(dif){dif._fr.lead='Les difficultés méthodologiques sont présentées avant les perspectives afin que les décisions futures découlent de contraintes déjà identifiées.';dif._fr.notes=note('Transformer les difficultés en critères de décision.',['Synchronisation olfactive et respiration.','Multiplication des appareils et des logs.','Charge participant et robustesse des analyses.'],'Ne pas présenter les difficultés comme des problèmes résolus définitivement.','Passer au bilan doctoral et aux compétences construites.')}
 const retro=find('Rétroplanning des études centrales');if(retro){retro._fr.lead='La séquence opérationnelle retenue est SOFT, puis OASIS, puis TWIXOLF, afin de consolider les contraintes techniques avant les collectes les plus dépendantes de la synchronisation olfactive.';retro._fr.notes=note('Présenter le calendrier comme une conséquence des contraintes précédentes.',['SOFT sécurise la logique onset/offset et les mesures.','OASIS tourne avant TWIXOLF.','TWIXAV et VIBEX continuent en analyses et valorisation.'],'L’ordre est opérationnel, pas hiérarchique scientifiquement.','Passer à l’enseignement et aux formations de l’année 2.')}
 const comm=find('Communications envisagées');if(comm){comm._fr.lead='Les actions de diffusion sont volontairement placées après le rétroplanning expérimental, pour maintenir une progression narrative centrée d’abord sur les collectes, les analyses et la faisabilité.';comm._fr.notes=note('Présenter les communications comme de la valorisation située dans le calendrier.',['Nuit des chercheurs : septembre 2026.','Fête de la Science : octobre 2026.','Expérimentarium : mars 2027.','FJC et JDD : juin 2027.'],'Ne pas ouvrir de nouvelles expériences à ce moment de la présentation.','Passer aux arbitrages à discuter.')}
 const desired=["Y a-t-il un espace-temps","Un récit en quatre mouvements","D'un parcours généraliste","Encadrement, équipe","Deux axes pour interroger","L'olfaction complique","Dix études principales","État d'avancement","TWIXAV -","Un effet net","De la fenêtre audiovisuelle","SOFT -","Transposer la liaison","VIBEX -","OASIS -","FLUXOLF -","Une plateforme expérimentale","Déclencher sur un événement physiologique","Une seule logique de traitement","Des sorties standardisées","La robustesse du protocole","Des développements logiciels","Les principales difficultés","La première année a aussi construit","Encadrement de mémoires de Master 1","Enseignement et formation - bilan","Enseignements réalisés","Formations suivies","Rétroplanning des études centrales","Enseignements prévus","Formations envisagées","Un horizon court","Passer de prototypes","Une progression conditionnelle","Les études futures prolongent","Trois prolongements possibles","Construire progressivement","Communications envisagées","Les arbitrages les plus utiles","Les décisions les plus utiles","Une première année passée","Repères bibliographiques - Axe 1","Repères bibliographiques - Axe 2","Merci pour votre attention"];
 const append=slides.filter(s=>s.appendix),main=slides.filter(s=>!s.appendix),out=[],seen=new Set();desired.forEach(k=>main.filter(s=>s.title&&s.title.includes(k)).forEach(s=>{if(!seen.has(s)){seen.add(s);out.push(s)}}));main.forEach(s=>{if(!seen.has(s)){seen.add(s);out.push(s)}});slides.splice(0,slides.length,...out,...append);
 const baseRender=w.renderSlides;if(typeof baseRender==='function'&&!w.__csiV13Render){w.__csiV13Render=true;w.renderSlides=function(){baseRender.apply(this,arguments);addChrome();paintChapter()}}
 const oldGo=w.goTo;if(typeof oldGo==='function'&&!w.__csiV13Go){w.__csiV13Go=true;w.goTo=function(index,pushHash=true){const cur=Number(d.querySelector('.slide.active')?.dataset.index||0);d.body.dataset.csiDir=index<cur?'prev':'next';oldGo.call(this,index,pushHash);addChrome();paintChapter()}}
 if(typeof w.visibleIndexes==='function'&&!w.__csiV13Move){w.__csiV13Move=true;w.move=function(delta){const vis=w.visibleIndexes();const cur=Number(d.querySelector('.slide.active')?.dataset.index||0);const pos=vis.indexOf(cur);const next=Math.max(0,Math.min(vis.length-1,pos+delta));w.goTo(vis[next])}}
 const oldUpdate=w.updateUI;if(typeof oldUpdate==='function'&&!w.__csiV13Update){w.__csiV13Update=true;w.updateUI=function(){oldUpdate.apply(this,arguments);addChrome();paintChapter();const v=d.getElementById('csiVersion');if(v)v.textContent=VERSION}}
 const L=localStorage.getItem('csi-lang')||'fr';slides.forEach(x=>{const v=L==='en'?x._en:x._fr;if(v){x.section=v.section;x.kicker=v.kicker;x.title=v.title;x.lead=v.lead;x.content=v.content;x.notes=v.notes}});
 if(typeof w.renderSlides==='function')w.renderSlides();if(typeof w.goTo==='function')w.goTo(0,false);addChrome();paintChapter();
});
})();
