(function(){
  const frame=document.getElementById('presentation');
  if(!frame) return;
  frame.addEventListener('load',()=>{
    try{
      const w=frame.contentWindow;
      const d=w.document;
      const slides=w.eval('slides');
      const find=t=>slides.find(s=>s.title&&s.title.includes(t));
      const refs=t=>`<div class="csi-ref"><strong>Références :</strong> ${t}</div>`;
      d.documentElement.style.setProperty('--page-width','1640px');
      const css=`
        :root{--csi-gap:16px;--csi-radius:22px;--csi-radius-sm:16px;--csi-border:1px solid var(--line)}
        body{background:linear-gradient(180deg,var(--cream),var(--accent-pale))!important}
        .appbar{width:min(1440px,calc(100vw - 28px))!important;background:color-mix(in srgb,var(--cream) 93%,transparent)!important;border:var(--csi-border)!important;box-shadow:0 12px 34px color-mix(in srgb,var(--accent-strong) 13%,transparent)!important}
        .brand-mark{border-radius:11px!important}.app-actions{gap:4px!important}.icon-btn,.pill-btn{min-height:38px!important}
        .slide{align-items:flex-start!important;overflow-y:auto!important;scrollbar-width:none!important;padding:96px clamp(34px,4vw,76px) 92px!important}
        .slide::-webkit-scrollbar{display:none}.slide-shell{width:min(var(--page-width),100%)!important;margin:auto!important;align-self:flex-start!important}
        .slide-kicker{margin-bottom:11px!important}.slide h2{font-size:clamp(2.15rem,3.95vw,4.35rem)!important;line-height:1.01!important;letter-spacing:-.045em!important;max-width:1380px!important;margin:0 0 14px!important}
        .lead{max-width:1300px!important;font-size:clamp(1rem,1.25vw,1.18rem)!important;line-height:1.5!important;margin:0 0 24px!important}.slide-content{align-content:start!important}
        .grid,.project-map,.roadmap,.result-strip,.hardware{gap:var(--csi-gap)!important}
        .card,.axis-card,.flow-card,.roadmap-card,.result,.question,.status-row,.callout{border-radius:var(--csi-radius)!important;border:var(--csi-border)!important;box-shadow:0 10px 28px color-mix(in srgb,var(--accent-strong) 9%,transparent)!important}
        .card,.axis-card,.roadmap-card,.flow-card{padding:21px!important}.callout{padding:16px 18px!important;border-left:4px solid var(--accent)!important}.bridge{border-radius:18px!important;margin-top:16px!important;padding:14px 17px!important}
        .card h3,.axis-card h3,.roadmap-card h3{font-size:clamp(1.12rem,1.45vw,1.45rem)!important;line-height:1.14!important;margin-bottom:7px!important}.card p,.card li,.axis-card p,.roadmap-card li{line-height:1.48!important}
        .timeline{gap:14px!important}.timeline-item h3{font-size:1.08rem!important}.timeline-item p{font-size:.86rem!important}.flow{gap:10px!important}.flow-card{padding:18px!important}.flow-card p{font-size:.91rem!important}.result{padding:17px!important}.result .pval{font-size:1.72rem!important}
        .navigator,.drawer,.notes-panel{background:color-mix(in srgb,var(--cream) 96%,var(--accent-pale))!important;color:var(--text)!important;border-color:var(--line)!important;box-shadow:0 24px 70px color-mix(in srgb,var(--accent-strong) 18%,transparent)!important}
        .navigator{width:min(430px,92vw)!important}.panel-head{border-color:var(--line)!important}.nav-search{background:var(--white)!important;color:var(--text)!important;border:1px solid var(--line)!important;border-radius:15px!important;outline:none!important}.nav-search:focus{border-color:var(--accent)!important;box-shadow:0 0 0 3px color-mix(in srgb,var(--accent) 16%,transparent)!important}
        .slide-list{gap:7px!important}.slide-link{background:transparent!important;color:var(--text)!important;border:1px solid transparent!important;border-radius:16px!important;padding:10px 11px!important}.slide-link:hover{background:var(--accent-pale)!important;border-color:var(--line)!important}.slide-link .n{background:var(--accent-soft)!important;color:var(--accent-strong)!important}.slide-link .t{color:var(--text)!important}.slide-link.active{background:var(--accent-soft)!important;border-color:color-mix(in srgb,var(--accent) 36%,transparent)!important}.slide-link.active .n{background:var(--accent)!important;color:#fff!important}.slide-link.active .t{color:var(--accent-strong)!important}
        html[data-theme="dark"] .navigator,html[data-theme="dark"] .drawer,html[data-theme="dark"] .notes-panel{background:color-mix(in srgb,var(--cream) 86%,var(--accent-pale))!important}.overview{background:color-mix(in srgb,var(--cream) 96%,transparent)!important}.overview-card{background:var(--white)!important;color:var(--text)!important;border:1px solid var(--line)!important}.overview-card:hover{border-color:var(--accent)!important;background:var(--accent-pale)!important}
        .csi-ref{margin-top:12px;padding-top:8px;border-top:1px solid var(--line);font-size:.69rem;color:var(--muted)}.csi-ref strong{color:var(--accent-strong)}
        .csi-logo-tray{margin-top:20px;display:grid;grid-template-columns:repeat(6,minmax(88px,1fr));gap:10px;padding:11px;border-radius:20px;background:#fff;box-shadow:0 12px 30px rgba(0,0,0,.13);max-width:980px}.csi-logo-tray .logo-cell{height:68px;border:1px solid #ececec;border-radius:13px;display:grid;place-items:center;padding:7px;background:#fff;overflow:hidden}.csi-logo-tray img{max-width:100%;max-height:54px;object-fit:contain}.csi-logo-fallback{font:900 .9rem system-ui;color:#24372f;text-align:center;line-height:1.05}
        .csi-members{margin-top:14px;padding:13px 15px;border:1px solid rgba(255,255,255,.22);border-radius:17px;background:rgba(255,255,255,.09)}.csi-members .mono{margin-bottom:5px}.csi-members strong{display:block;margin-top:4px}
        .csi-device-inline{display:grid;grid-template-columns:190px minmax(0,1fr);gap:18px;align-items:center;margin-top:16px;padding:14px;border-radius:20px;background:var(--white);border:1px solid var(--line);box-shadow:0 10px 28px color-mix(in srgb,var(--accent-strong) 8%,transparent)}.csi-device-inline img{width:190px;height:116px;object-fit:contain;border-radius:14px;background:#fff}.csi-device-inline h3{margin:0 0 5px;color:var(--accent-strong);font:800 1.12rem Georgia,serif}.csi-device-inline p{margin:0;color:var(--muted);font-size:.9rem}
        .csi-equip-pair{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:16px}.csi-mini-device{display:grid;grid-template-columns:126px 1fr;gap:13px;align-items:center;padding:13px;border:1px solid var(--line);border-radius:19px;background:var(--white)}.csi-mini-device img{width:126px;height:92px;object-fit:contain;border-radius:12px;background:#fff}.csi-mini-device h3{margin:0 0 4px;color:var(--accent-strong);font:800 1.02rem Georgia,serif}.csi-mini-device p{margin:0;color:var(--muted);font-size:.84rem;line-height:1.38}
        .csi-diffusion{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;position:relative}.csi-diffusion::before{content:"";position:absolute;left:5%;right:5%;top:27px;height:2px;background:var(--accent-soft)}.csi-diff{position:relative;z-index:1;padding:0 5px}.csi-diff .dot{width:54px;height:54px;border-radius:17px;display:grid;place-items:center;background:var(--accent);color:#fff;font-weight:950;margin-bottom:13px;box-shadow:0 8px 18px color-mix(in srgb,var(--accent) 25%,transparent)}.csi-diff h3{margin:0 0 4px;color:var(--accent-strong);font:800 1.03rem Georgia,serif;line-height:1.1}.csi-diff p{margin:0;color:var(--muted);font-size:.84rem}
        .csi-retro{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}.csi-retro>div{border:1px solid var(--line);border-radius:18px;background:var(--white);padding:15px;box-shadow:0 8px 24px color-mix(in srgb,var(--accent-strong) 8%,transparent)}.csi-retro h3{margin:8px 0 5px;color:var(--accent-strong);font:800 1rem Georgia,serif}.csi-retro p{font-size:.79rem;line-height:1.4;color:var(--muted);margin:0}.csi-date{font-size:.69rem;text-transform:uppercase;letter-spacing:.07em;color:var(--accent);font-weight:950}
        .question-list{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:11px!important}.question-list .question{padding:14px!important;min-height:0!important;grid-template-columns:40px 1fr!important}.question-list .question::before{width:36px!important;height:36px!important;border-radius:12px!important}.question-list .question strong{color:var(--accent-strong)}
        #csiQVault{position:fixed;inset:0;z-index:3000;background:linear-gradient(180deg,var(--cream),var(--accent-pale));display:none;overflow:auto;color:var(--text)}.csi-q-inner{width:min(1640px,100%);min-height:100vh;margin:auto;padding:92px clamp(34px,4vw,76px) 70px}.csi-q-head{display:flex;justify-content:space-between;align-items:center;gap:18px}.csi-q-close{border:1px solid var(--line);background:var(--white);color:var(--text);border-radius:999px;padding:10px 15px;font-weight:900;cursor:pointer}.csi-q-blank{margin-top:30px;min-height:58vh;border:1px dashed var(--line);border-radius:28px;background:var(--white)}
        @media(max-width:1220px){.csi-logo-tray{grid-template-columns:repeat(3,1fr)}.csi-retro{grid-template-columns:repeat(3,1fr)}.csi-diffusion{grid-template-columns:repeat(5,minmax(135px,1fr));overflow-x:auto;padding-bottom:8px}.csi-diffusion::before{display:none}}
        @media(max-width:900px){.csi-equip-pair{grid-template-columns:1fr}.csi-device-inline{grid-template-columns:1fr}.csi-device-inline img{width:100%;height:170px}.question-list{grid-template-columns:1fr!important}.csi-retro{grid-template-columns:repeat(2,1fr)}}
      `;
      const st=d.createElement('style');st.textContent=css;d.head.appendChild(st);
      [...d.querySelectorAll('.control-section')].forEach(sec=>{const lab=sec.querySelector('.control-label');if(lab&&lab.textContent.trim()==='Raccourcis')sec.remove();});
      const cover=find("Y a-t-il un espace-temps pour les odeurs ?");
      if(cover){cover.hero=true;cover.content=`<div><span class="eyebrow">Doctorat en psychologie cognitive · CSI-1</span><h1>Y a-t-il un espace-temps pour les odeurs&nbsp;?</h1><p class="subtitle">Mécanismes d'intégration entre olfaction, vision et audition</p><div class="csi-logo-tray"><div class="logo-cell"><img src="https://til.u-bourgogne.fr/wp-content/uploads/2025/01/logo-UBE-drapeau-quadri.jpg" alt="Université Bourgogne Europe"></div><div class="logo-cell"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Cnrs-logo.svg" alt="CNRS"></div><div class="logo-cell"><img src="https://clienfarms.eu/wp-content/uploads/2022/05/inrae-vector-logo.png" alt="INRAE"></div><div class="logo-cell"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Logo%20Institut%20Agro%202022.png" alt="Institut Agro Dijon"></div><div class="logo-cell"><img src="https://fjc-2024.sciencesconf.org/data/pages/CSGA_1.png" alt="CSGA" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'csi-logo-fallback',textContent:'CSGA · Centre des Sciences du Goût et de l’Alimentation'}))"></div><div class="logo-cell"><img src="https://u1093.ube.fr/app/smush-webp/2026/04/logo-ES.jpg.webp" alt="École Doctorale Environnements-Santé"></div></div></div><aside class="identity-card"><div class="mono">Doctorant</div><strong>Luc PERROQUIN</strong><div class="identity-list"><div class="identity-row"><div class="mono">Direction</div><strong>Renaud BROCHARD</strong><br>Professeur des Universités - directeur</div><div class="identity-row"><div class="mono">Co-direction</div><strong>Arnaud LELEU</strong><br>Maître de conférences</div><div class="identity-row"><div class="mono">Équipe</div><strong>DOCC - CSGA</strong><br>Université Bourgogne Europe</div></div><div class="csi-members"><div class="mono">Comité de Suivi Individuel</div><strong>Fabrice Damon</strong><strong>Camille Ferdenzi-Lemaître</strong></div></aside>`;}
      const time=find("L'intégration multisensorielle");if(time)time.content+=refs("Vroomen & Keetels, 2010 ; Keetels & Vroomen, 2012 ; Powers et al., 2009 ; Stevenson et al., 2012 ; Stein & Stanford, 2008.");
      const olf=find("L'olfaction complique le problème temporel");if(olf){olf.content+=`<div class="csi-device-inline"><img src="https://www.cynexo.com/wp-content/uploads/2018/09/sniff-O-foto5.jpg" alt="CyNexo Sniff-0"><div><h3>CyNexo Sniff-0 + Spir-0</h3><p>L'appareillage intervient ici parce que le problème théorique dépend directement de la délivrance odorante, du temps de transit et de la respiration.</p></div></div>${refs("Gotow & Kobayakawa, 2017 ; Mainland & Sobel, 2006 ; Sela & Sobel, 2010.")}`;}
      const scene=find("La perception de scène");if(scene)scene.content+=refs("Intraub & Richardson, 1989 ; Intraub, 2012 ; Gagnier et al., 2013 ; Bainbridge & Baker, 2020 ; Park et al., 2024.");
      const soft=find("Mesurer le temps propre de chaque modalité");if(soft){soft.title="SOFT - dissocier onset, offset et durée";soft.lead="SOFT teste directement une explication possible de l'asymétrie observée avec TWIXAV, tout en reliant comportement, EEG et physiologie périphérique.";soft.content+=`<div class="csi-equip-pair"><div class="csi-mini-device"><img src="https://www.biosemi.com/pics/cap_128_medium1_large.jpg" alt="BioSemi ActiveTwo 128 canaux"><div><h3>BioSemi ActiveTwo</h3><p>L'EEG 128 canaux permet de marquer et comparer les dynamiques cérébrales associées aux événements sensoriels.</p></div></div><div class="csi-mini-device"><img src="https://img.medicalexpo.com/images_me/photo-g/126111-14323895.jpg" alt="BIOPAC MP160"><div><h3>BIOPAC MP160</h3><p>EDA, ECG et autres voies physiologiques complètent les mesures comportementales lorsque le protocole le nécessite.</p></div></div></div>${refs("Vroomen & Keetels, 2010 ; Keetels & Vroomen, 2012 ; Powers et al., 2009.")}`;}
      const oasis=find("OASIS - relier odeur");if(oasis){oasis.kicker="OASIS - prochaine collecte";oasis.lead="OASIS est planifiée avant TWIXOLF dans le rétroplanning 2026-2027.";oasis.content+=refs("Rekow et al., 2022 ; Hörberg et al., 2020 ; Gottfried, 2010.");}
      const twixolf=find("Transposer la liaison temporelle à l'olfaction");if(twixolf){twixolf.kicker="TWIXOLF - après OASIS";twixolf.lead="TWIXOLF reste l'étude centrale de transposition olfactive de l'Axe 1, mais elle est programmée après OASIS dans la séquence opérationnelle.";twixolf.content+=refs("Gotow & Kobayakawa, 2017 ; Keetels & Vroomen, 2012 ; Sela & Sobel, 2010.");}
      const difficulties=find("Les principales difficultés ont déjà modifié");if(difficulties){difficulties.section="Infrastructure";difficulties.kicker="Difficultés expérimentales";difficulties.title="Les contraintes techniques qui conditionnent la suite";difficulties.lead="Ces difficultés sont présentées avant les perspectives car elles déterminent directement ce qui peut être lancé, dans quel ordre et avec quel niveau de complexité.";difficulties.content=`<div class="grid three"><div class="card"><h3>Olfaction</h3><p>Contrôler débit, délai physique, flush, habituation et relation entre commande et onset perceptif.</p></div><div class="card"><h3>Respiration</h3><p>Détecter le début d'inspiration de manière stable et l'intégrer aux séquences sans bloquer l'expérience.</p></div><div class="card"><h3>Synchronisation</h3><p>Faire converger PsychoPy, Sniff-0, Spir-0, BioSemi et BIOPAC autour d'événements temporellement cohérents.</p></div><div class="card"><h3>EEG / TTL</h3><p>Conserver un codage lisible tout en respectant la limite 8 bits des triggers utilisés dans l'installation actuelle.</p></div><div class="card"><h3>PC expérimental</h3><p>Composer avec un environnement Windows 7 hors ligne, des dépendances anciennes et des contraintes d'installation.</p></div><div class="card"><h3>Charge participant</h3><p>Valider en pilote la durée réelle de préparation, les pauses, l'habituation olfactive et la tolérance globale de la session.</p></div></div>`;}
      const retro=find("Un horizon court centré sur la consolidation");if(retro){retro.section="Perspectives";retro.kicker="Rétroplanning 2026-2027";retro.title="Rétroplanning des manipulations";retro.lead="La séquence opérationnelle retenue place OASIS avant TWIXOLF, après la phase prioritaire consacrée à SOFT.";retro.content=`<div class="csi-retro"><div><div class="csi-date">Sept-Oct 2026</div><h3>SOFT - pilote</h3><p>Charge participant, onset/offset, triggers et matériel.</p></div><div><div class="csi-date">Oct-Déc 2026</div><h3>SOFT - collecte</h3><p>Collecte prioritaire et analyses intermédiaires.</p></div><div><div class="csi-date">Jan-Mars 2027</div><h3>OASIS</h3><p>Prétests odorants et physiologiques, puis collecte spatiale.</p></div><div><div class="csi-date">Avr-Juin 2027</div><h3>TWIXOLF</h3><p>Prétests puis collecte temporelle olfactive.</p></div><div><div class="csi-date">En parallèle</div><h3>TWIXAV + VIBEX</h3><p>Analyses finales, figures et rédaction.</p></div><div><div class="csi-date">2027-2028</div><h3>Extensions</h3><p>Seulement selon résultats, temps et faisabilité.</p></div></div>`;}
      const comm=find("Rendre la recherche visible, compréhensible et recrutante");if(comm){comm.section="Valorisation";comm.kicker="Diffusion scientifique";comm.title="Diffusions envisagées en 2026-2027";comm.lead="Une seule ligne chronologique, de septembre 2026 à juin 2027.";comm.content=`<div class="csi-diffusion"><div class="csi-diff"><div class="dot">09</div><h3>Nuit des chercheurs</h3><p>Septembre 2026</p></div><div class="csi-diff"><div class="dot">10</div><h3>Fête de la Science</h3><p>Octobre 2026</p></div><div class="csi-diff"><div class="dot">03</div><h3>Expérimentarium</h3><p>Mars 2027</p></div><div class="csi-diff"><div class="dot">06</div><h3>FJC</h3><p>Juin 2027</p></div><div class="csi-diff"><div class="dot">06</div><h3>JDD</h3><p>Juin 2027</p></div></div>`;}
      const decisions=find("Les décisions les plus utiles à discuter aujourd'hui");if(decisions){decisions.kicker="Décisions à discuter";decisions.lead="Le CSI peut aider à sécuriser les choix qui conditionnent la faisabilité de l'année 2.";decisions.content=`<div class="question-list"><div class="question"><div><strong>Ordre des manipulations</strong><br>Valider SOFT → OASIS → TWIXOLF et le niveau acceptable de chevauchement collecte/analyse.</div></div><div class="question"><div><strong>Périmètre de SOFT</strong><br>Durée de session, place de l'EEG/physiologie et critères de simplification si le pilote est trop lourd.</div></div><div class="question"><div><strong>Matériel</strong><br>Identifier les éléments à sécuriser pour limiter panne et incompatibilité.</div></div><div class="question"><div><strong>Valorisation</strong><br>Prioriser le short paper VIBEX puis TWIXAV selon la solidité des analyses.</div></div><div class="question"><div><strong>Extensions</strong><br>Définir les critères qui justifieraient SORBET, SOLAR, COBEX, BRAUD ou BRAUDOLF.</div></div><div class="question"><div><strong>Charge doctorale</strong><br>Préserver l'équilibre entre collectes, enseignement, formations et communications.</div></div></div>`;}
      slides.forEach(s=>{if(!s.content)return;s.content=s.content.replace(/<div class="callout"[^>]*>[^<]*Les références détaillées[\s\S]*?<\/div>/gi,'');s.content=s.content.replace(/<div class="callout"[^>]*>[^<]*Les références complètes[\s\S]*?<\/div>/gi,'');});
      const thanks={section:"Remerciements",kicker:"Remerciements",title:"Merci",lead:"Merci aux membres du Comité de Suivi Individuel et à l'équipe d'encadrement pour les échanges consacrés à l'avancement du doctorat.",content:`<div class="grid two"><div class="card dark"><h3>Comité de Suivi Individuel</h3><p><strong>Fabrice Damon</strong></p><p style="margin-top:9px"><strong>Camille Ferdenzi-Lemaître</strong></p></div><div class="card"><h3>Direction de thèse</h3><p><strong>Renaud Brochard</strong> - directeur</p><p style="margin-top:9px"><strong>Arnaud Leleu</strong> - co-directeur</p></div></div><div class="csi-logo-tray"><div class="logo-cell"><img src="https://til.u-bourgogne.fr/wp-content/uploads/2025/01/logo-UBE-drapeau-quadri.jpg" alt="Université Bourgogne Europe"></div><div class="logo-cell"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Cnrs-logo.svg" alt="CNRS"></div><div class="logo-cell"><img src="https://clienfarms.eu/wp-content/uploads/2022/05/inrae-vector-logo.png" alt="INRAE"></div><div class="logo-cell"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Logo%20Institut%20Agro%202022.png" alt="Institut Agro Dijon"></div><div class="logo-cell"><img src="https://fjc-2024.sciencesconf.org/data/pages/CSGA_1.png" alt="CSGA" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'csi-logo-fallback',textContent:'CSGA · Centre des Sciences du Goût et de l’Alimentation'}))"></div><div class="logo-cell"><img src="https://u1093.ube.fr/app/smush-webp/2026/04/logo-ES.jpg.webp" alt="École Doctorale Environnements-Santé"></div></div>`};
      const appendix=slides.filter(s=>s.appendix);let main=slides.filter(s=>!s.appendix);
      const futureTemporal=find("Les études futures prolongent");const futureSpatial=slides.find(s=>s.title&&(/prolongements possibles|extensions possibles/i.test(s.title)));const roadmap=find("Une progression conditionnelle plutôt qu'un calendrier rigide");const professional=find("Construire progressivement un profil de maître de conférences");const ref1=find("Repères bibliographiques - Axe 1");const ref2=find("Repères bibliographiques - Axe 2");
      const moving=[futureTemporal,futureSpatial,comm].filter(Boolean);main=main.filter(s=>!moving.includes(s));let idx=main.indexOf(difficulties);if(idx>=0)main.splice(idx+1,0,...[futureTemporal,futureSpatial].filter(Boolean));const anchor=professional||roadmap;idx=main.indexOf(anchor);if(comm){if(idx>=0)main.splice(idx+1,0,comm);else{const di=main.indexOf(decisions);main.splice(di>=0?di:main.length,0,comm);}}
      [ref1,ref2].filter(Boolean).forEach(r=>{const i=main.indexOf(r);if(i>=0)main.splice(i,1);});if(ref1)main.push(ref1);if(ref2)main.push(ref2);main.push(thanks);slides.splice(0,slides.length,...main,...appendix);
      w.renderSlides();w.goTo(0,false);
      const actions=d.querySelector('.app-actions');if(actions&&!d.getElementById('csiQBtn')){const b=d.createElement('button');b.className='icon-btn';b.id='csiQBtn';b.type='button';b.textContent='Q';b.title='Questions spécifiques';actions.insertBefore(b,d.getElementById('settingsBtn'));const v=d.createElement('section');v.id='csiQVault';v.innerHTML=`<div class="csi-q-inner"><div class="csi-q-head"><div><div class="slide-kicker">Slides cachées</div><h2 style="font-family:Georgia,serif;font-size:clamp(2.5rem,5vw,5rem);margin:.25em 0 0">Questions spécifiques</h2></div><button class="csi-q-close">Retour</button></div><div class="csi-q-blank"></div></div>`;d.body.appendChild(v);b.onclick=()=>v.style.display='block';v.querySelector('.csi-q-close').onclick=()=>v.style.display='none';}
      d.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(d.activeElement?.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();e.stopImmediatePropagation();w.move(1);return;}if(e.key==='ArrowLeft'){e.preventDefault();e.stopImmediatePropagation();w.move(-1);return;}e.preventDefault();e.stopImmediatePropagation();},true);
    }catch(err){console.error('CSI v10',err);}
  });
})();